package com.epbt2.mtkn.tanya.dao;


import com.epbt2.util.NotFoundException;
import java.sql.*;
import java.util.*;


 /**
  * HVcmk1 Data Access Object (DAO).
  * This class contains all database handling that is needed to 
  * permanently store and retrieve HVcmk1 object instances. 
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HVcmk1Dao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public HVcmk1 createValueObject() {
          return new HVcmk1();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public HVcmk1 getObject(Connection conn, String CMpamsms) throws NotFoundException, SQLException {

          HVcmk1 valueObject = createValueObject();
          valueObject.setCMpamsms(CMpamsms);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, HVcmk1 valueObject) throws NotFoundException, SQLException {

          if (valueObject.getCMpamsms() == null) {
               //System.out.println("Can not select without Primary-Key!");
               throw new NotFoundException("Can not select without Primary-Key!");
          }

          String sql = "SELECT * FROM mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5 WHERE (CMP_AMSMS = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setString(1, valueObject.getCMpamsms()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5 ORDER BY CMP_AMSMS ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, HVcmk1 valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5 ( CMP_AMSMS, CMP_AMTGK, CMP_BYSMS, "
               + "CMP_BYTGK, CMN_AMSMS, CMN_AMTGK, "
               + "CMN_BYSMS, CMN_BYTGK, CMB_AMSMS, "
               + "CMB_AMTGK, CMB_BYSMS, CMB_BYTGK, "
               + "CMP_BKSMS, CMP_BKTGK, CMN_BKSMS, "
               + "CMN_BKTGK, CMB_BKSMS, CMB_BKTGK, "
               + "CMP_LEBH1, CMB_LEBH1, CMN_LEBH1) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setString(1, valueObject.getCMpamsms()); 
               stmt.setString(2, valueObject.getCMpamtgk()); 
               stmt.setString(3, valueObject.getCMpbysms()); 
               stmt.setString(4, valueObject.getCMpbytgk()); 
               stmt.setString(5, valueObject.getCMnamsms()); 
               stmt.setString(6, valueObject.getCMnamtgk()); 
               stmt.setString(7, valueObject.getCMnbysms()); 
               stmt.setString(8, valueObject.getCMnbytgk()); 
               stmt.setString(9, valueObject.getCMbamsms()); 
               stmt.setString(10, valueObject.getCMbamtgk()); 
               stmt.setString(11, valueObject.getCMbbysms()); 
               stmt.setString(12, valueObject.getCMbbytgk()); 
               stmt.setString(13, valueObject.getCMpbksms()); 
               stmt.setString(14, valueObject.getCMpbktgk()); 
               stmt.setString(15, valueObject.getCMnbksms()); 
               stmt.setString(16, valueObject.getCMnbktgk()); 
               stmt.setString(17, valueObject.getCMbbksms()); 
               stmt.setString(18, valueObject.getCMbbktgk()); 
               stmt.setString(19, valueObject.getCMplebh1()); 
               stmt.setString(20, valueObject.getCMblebh1()); 
               stmt.setString(21, valueObject.getCMnlebh1()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, HVcmk1 valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5 SET CMP_AMTGK = ?, CMP_BYSMS = ?, CMP_BYTGK = ?, "
               + "CMN_AMSMS = ?, CMN_AMTGK = ?, CMN_BYSMS = ?, "
               + "CMN_BYTGK = ?, CMB_AMSMS = ?, CMB_AMTGK = ?, "
               + "CMB_BYSMS = ?, CMB_BYTGK = ?, CMP_BKSMS = ?, "
               + "CMP_BKTGK = ?, CMN_BKSMS = ?, CMN_BKTGK = ?, "
               + "CMB_BKSMS = ?, CMB_BKTGK = ?, CMP_LEBH1 = ?, "
               + "CMB_LEBH1 = ?, CMN_LEBH1 = ? WHERE (CMP_AMSMS = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getCMpamtgk()); 
              stmt.setString(2, valueObject.getCMpbysms()); 
              stmt.setString(3, valueObject.getCMpbytgk()); 
              stmt.setString(4, valueObject.getCMnamsms()); 
              stmt.setString(5, valueObject.getCMnamtgk()); 
              stmt.setString(6, valueObject.getCMnbysms()); 
              stmt.setString(7, valueObject.getCMnbytgk()); 
              stmt.setString(8, valueObject.getCMbamsms()); 
              stmt.setString(9, valueObject.getCMbamtgk()); 
              stmt.setString(10, valueObject.getCMbbysms()); 
              stmt.setString(11, valueObject.getCMbbytgk()); 
              stmt.setString(12, valueObject.getCMpbksms()); 
              stmt.setString(13, valueObject.getCMpbktgk()); 
              stmt.setString(14, valueObject.getCMnbksms()); 
              stmt.setString(15, valueObject.getCMnbktgk()); 
              stmt.setString(16, valueObject.getCMbbksms()); 
              stmt.setString(17, valueObject.getCMbbktgk()); 
              stmt.setString(18, valueObject.getCMplebh1()); 
              stmt.setString(19, valueObject.getCMblebh1()); 
              stmt.setString(20, valueObject.getCMnlebh1()); 

              stmt.setString(21, valueObject.getCMpamsms()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, HVcmk1 valueObject) 
          throws NotFoundException, SQLException {

          if (valueObject.getCMpamsms() == null) {
               //System.out.println("Can not delete without Primary-Key!");
               throw new NotFoundException("Can not delete without Primary-Key!");
          }

          String sql = "DELETE FROM mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5 WHERE (CMP_AMSMS = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getCMpamsms()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, HVcmk1 valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5 WHERE 1=1 ");

          if (valueObject.getCMpamsms() != null) {
              if (first) { first = false; }
              sql.append("AND CMP_AMSMS LIKE '").append(valueObject.getCMpamsms()).append("%' ");
          }

          if (valueObject.getCMpamtgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMP_AMTGK LIKE '").append(valueObject.getCMpamtgk()).append("%' ");
          }

          if (valueObject.getCMpbysms() != null) {
              if (first) { first = false; }
              sql.append("AND CMP_BYSMS LIKE '").append(valueObject.getCMpbysms()).append("%' ");
          }

          if (valueObject.getCMpbytgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMP_BYTGK LIKE '").append(valueObject.getCMpbytgk()).append("%' ");
          }

          if (valueObject.getCMnamsms() != null) {
              if (first) { first = false; }
              sql.append("AND CMN_AMSMS LIKE '").append(valueObject.getCMnamsms()).append("%' ");
          }

          if (valueObject.getCMnamtgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMN_AMTGK LIKE '").append(valueObject.getCMnamtgk()).append("%' ");
          }

          if (valueObject.getCMnbysms() != null) {
              if (first) { first = false; }
              sql.append("AND CMN_BYSMS LIKE '").append(valueObject.getCMnbysms()).append("%' ");
          }

          if (valueObject.getCMnbytgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMN_BYTGK LIKE '").append(valueObject.getCMnbytgk()).append("%' ");
          }

          if (valueObject.getCMbamsms() != null) {
              if (first) { first = false; }
              sql.append("AND CMB_AMSMS LIKE '").append(valueObject.getCMbamsms()).append("%' ");
          }

          if (valueObject.getCMbamtgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMB_AMTGK LIKE '").append(valueObject.getCMbamtgk()).append("%' ");
          }

          if (valueObject.getCMbbysms() != null) {
              if (first) { first = false; }
              sql.append("AND CMB_BYSMS LIKE '").append(valueObject.getCMbbysms()).append("%' ");
          }

          if (valueObject.getCMbbytgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMB_BYTGK LIKE '").append(valueObject.getCMbbytgk()).append("%' ");
          }

          if (valueObject.getCMpbksms() != null) {
              if (first) { first = false; }
              sql.append("AND CMP_BKSMS LIKE '").append(valueObject.getCMpbksms()).append("%' ");
          }

          if (valueObject.getCMpbktgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMP_BKTGK LIKE '").append(valueObject.getCMpbktgk()).append("%' ");
          }

          if (valueObject.getCMnbksms() != null) {
              if (first) { first = false; }
              sql.append("AND CMN_BKSMS LIKE '").append(valueObject.getCMnbksms()).append("%' ");
          }

          if (valueObject.getCMnbktgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMN_BKTGK LIKE '").append(valueObject.getCMnbktgk()).append("%' ");
          }

          if (valueObject.getCMbbksms() != null) {
              if (first) { first = false; }
              sql.append("AND CMB_BKSMS LIKE '").append(valueObject.getCMbbksms()).append("%' ");
          }

          if (valueObject.getCMbbktgk() != null) {
              if (first) { first = false; }
              sql.append("AND CMB_BKTGK LIKE '").append(valueObject.getCMbbktgk()).append("%' ");
          }

          if (valueObject.getCMplebh1() != null) {
              if (first) { first = false; }
              sql.append("AND CMP_LEBH1 LIKE '").append(valueObject.getCMplebh1()).append("%' ");
          }

          if (valueObject.getCMblebh1() != null) {
              if (first) { first = false; }
              sql.append("AND CMB_LEBH1 LIKE '").append(valueObject.getCMblebh1()).append("%' ");
          }

          if (valueObject.getCMnlebh1() != null) {
              if (first) { first = false; }
              sql.append("AND CMN_LEBH1 LIKE '").append(valueObject.getCMnlebh1()).append("%' ");
          }


          sql.append("ORDER BY CMP_AMSMS ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, HVcmk1 valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setCMpamsms(result.getString("CMP_AMSMS")); 
                   valueObject.setCMpamtgk(result.getString("CMP_AMTGK")); 
                   valueObject.setCMpbysms(result.getString("CMP_BYSMS")); 
                   valueObject.setCMpbytgk(result.getString("CMP_BYTGK")); 
                   valueObject.setCMnamsms(result.getString("CMN_AMSMS")); 
                   valueObject.setCMnamtgk(result.getString("CMN_AMTGK")); 
                   valueObject.setCMnbysms(result.getString("CMN_BYSMS")); 
                   valueObject.setCMnbytgk(result.getString("CMN_BYTGK")); 
                   valueObject.setCMbamsms(result.getString("CMB_AMSMS")); 
                   valueObject.setCMbamtgk(result.getString("CMB_AMTGK")); 
                   valueObject.setCMbbysms(result.getString("CMB_BYSMS")); 
                   valueObject.setCMbbytgk(result.getString("CMB_BYTGK")); 
                   valueObject.setCMpbksms(result.getString("CMP_BKSMS")); 
                   valueObject.setCMpbktgk(result.getString("CMP_BKTGK")); 
                   valueObject.setCMnbksms(result.getString("CMN_BKSMS")); 
                   valueObject.setCMnbktgk(result.getString("CMN_BKTGK")); 
                   valueObject.setCMbbksms(result.getString("CMB_BKSMS")); 
                   valueObject.setCMbbktgk(result.getString("CMB_BKTGK")); 
                   valueObject.setCMplebh1(result.getString("CMP_LEBH1")); 
                   valueObject.setCMblebh1(result.getString("CMB_LEBH1")); 
                   valueObject.setCMnlebh1(result.getString("CMN_LEBH1")); 

              } else {
                    //System.out.println("HVcmk1 Object Not Found!");
                    throw new NotFoundException("HVcmk1 Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   HVcmk1 temp = createValueObject();

                   temp.setCMpamsms(result.getString("CMP_AMSMS")); 
                   temp.setCMpamtgk(result.getString("CMP_AMTGK")); 
                   temp.setCMpbysms(result.getString("CMP_BYSMS")); 
                   temp.setCMpbytgk(result.getString("CMP_BYTGK")); 
                   temp.setCMnamsms(result.getString("CMN_AMSMS")); 
                   temp.setCMnamtgk(result.getString("CMN_AMTGK")); 
                   temp.setCMnbysms(result.getString("CMN_BYSMS")); 
                   temp.setCMnbytgk(result.getString("CMN_BYTGK")); 
                   temp.setCMbamsms(result.getString("CMB_AMSMS")); 
                   temp.setCMbamtgk(result.getString("CMB_AMTGK")); 
                   temp.setCMbbysms(result.getString("CMB_BYSMS")); 
                   temp.setCMbbytgk(result.getString("CMB_BYTGK")); 
                   temp.setCMpbksms(result.getString("CMP_BKSMS")); 
                   temp.setCMpbktgk(result.getString("CMP_BKTGK")); 
                   temp.setCMnbksms(result.getString("CMN_BKSMS")); 
                   temp.setCMnbktgk(result.getString("CMN_BKTGK")); 
                   temp.setCMbbksms(result.getString("CMB_BKSMS")); 
                   temp.setCMbbktgk(result.getString("CMB_BKTGK")); 
                   temp.setCMplebh1(result.getString("CMP_LEBH1")); 
                   temp.setCMblebh1(result.getString("CMB_LEBH1")); 
                   temp.setCMnlebh1(result.getString("CMN_LEBH1")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}

