package com.epbt2.mtkn.tanya.dao;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * HVcmk1 Value Object.
  * This class is value object representing database table mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HVcmk1 implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String CMpamsms;
    private String CMpamtgk;
    private String CMpbysms;
    private String CMpbytgk;
    private String CMnamsms;
    private String CMnamtgk;
    private String CMnbysms;
    private String CMnbytgk;
    private String CMbamsms;
    private String CMbamtgk;
    private String CMbbysms;
    private String CMbbytgk;
    private String CMpbksms;
    private String CMpbktgk;
    private String CMnbksms;
    private String CMnbktgk;
    private String CMbbksms;
    private String CMbbktgk;
    private String CMplebh1;
    private String CMblebh1;
    private String CMnlebh1;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public HVcmk1 () {

    }

    public HVcmk1 (String CMpamsmsIn) {

          this.CMpamsms = CMpamsmsIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getCMpamsms() {
          return this.CMpamsms;
    }
    public void setCMpamsms(String CMpamsmsIn) {
          this.CMpamsms = CMpamsmsIn;
    }

    public String getCMpamtgk() {
          return this.CMpamtgk;
    }
    public void setCMpamtgk(String CMpamtgkIn) {
          this.CMpamtgk = CMpamtgkIn;
    }

    public String getCMpbysms() {
          return this.CMpbysms;
    }
    public void setCMpbysms(String CMpbysmsIn) {
          this.CMpbysms = CMpbysmsIn;
    }

    public String getCMpbytgk() {
          return this.CMpbytgk;
    }
    public void setCMpbytgk(String CMpbytgkIn) {
          this.CMpbytgk = CMpbytgkIn;
    }

    public String getCMnamsms() {
          return this.CMnamsms;
    }
    public void setCMnamsms(String CMnamsmsIn) {
          this.CMnamsms = CMnamsmsIn;
    }

    public String getCMnamtgk() {
          return this.CMnamtgk;
    }
    public void setCMnamtgk(String CMnamtgkIn) {
          this.CMnamtgk = CMnamtgkIn;
    }

    public String getCMnbysms() {
          return this.CMnbysms;
    }
    public void setCMnbysms(String CMnbysmsIn) {
          this.CMnbysms = CMnbysmsIn;
    }

    public String getCMnbytgk() {
          return this.CMnbytgk;
    }
    public void setCMnbytgk(String CMnbytgkIn) {
          this.CMnbytgk = CMnbytgkIn;
    }

    public String getCMbamsms() {
          return this.CMbamsms;
    }
    public void setCMbamsms(String CMbamsmsIn) {
          this.CMbamsms = CMbamsmsIn;
    }

    public String getCMbamtgk() {
          return this.CMbamtgk;
    }
    public void setCMbamtgk(String CMbamtgkIn) {
          this.CMbamtgk = CMbamtgkIn;
    }

    public String getCMbbysms() {
          return this.CMbbysms;
    }
    public void setCMbbysms(String CMbbysmsIn) {
          this.CMbbysms = CMbbysmsIn;
    }

    public String getCMbbytgk() {
          return this.CMbbytgk;
    }
    public void setCMbbytgk(String CMbbytgkIn) {
          this.CMbbytgk = CMbbytgkIn;
    }

    public String getCMpbksms() {
          return this.CMpbksms;
    }
    public void setCMpbksms(String CMpbksmsIn) {
          this.CMpbksms = CMpbksmsIn;
    }

    public String getCMpbktgk() {
          return this.CMpbktgk;
    }
    public void setCMpbktgk(String CMpbktgkIn) {
          this.CMpbktgk = CMpbktgkIn;
    }

    public String getCMnbksms() {
          return this.CMnbksms;
    }
    public void setCMnbksms(String CMnbksmsIn) {
          this.CMnbksms = CMnbksmsIn;
    }

    public String getCMnbktgk() {
          return this.CMnbktgk;
    }
    public void setCMnbktgk(String CMnbktgkIn) {
          this.CMnbktgk = CMnbktgkIn;
    }

    public String getCMbbksms() {
          return this.CMbbksms;
    }
    public void setCMbbksms(String CMbbksmsIn) {
          this.CMbbksms = CMbbksmsIn;
    }

    public String getCMbbktgk() {
          return this.CMbbktgk;
    }
    public void setCMbbktgk(String CMbbktgkIn) {
          this.CMbbktgk = CMbbktgkIn;
    }

    public String getCMplebh1() {
          return this.CMplebh1;
    }
    public void setCMplebh1(String CMplebh1In) {
          this.CMplebh1 = CMplebh1In;
    }

    public String getCMblebh1() {
          return this.CMblebh1;
    }
    public void setCMblebh1(String CMblebh1In) {
          this.CMblebh1 = CMblebh1In;
    }

    public String getCMnlebh1() {
          return this.CMnlebh1;
    }
    public void setCMnlebh1(String CMnlebh1In) {
          this.CMnlebh1 = CMnlebh1In;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String CMpamsmsIn,
          String CMpamtgkIn,
          String CMpbysmsIn,
          String CMpbytgkIn,
          String CMnamsmsIn,
          String CMnamtgkIn,
          String CMnbysmsIn,
          String CMnbytgkIn,
          String CMbamsmsIn,
          String CMbamtgkIn,
          String CMbbysmsIn,
          String CMbbytgkIn,
          String CMpbksmsIn,
          String CMpbktgkIn,
          String CMnbksmsIn,
          String CMnbktgkIn,
          String CMbbksmsIn,
          String CMbbktgkIn,
          String CMplebh1In,
          String CMblebh1In,
          String CMnlebh1In) {
          this.CMpamsms = CMpamsmsIn;
          this.CMpamtgk = CMpamtgkIn;
          this.CMpbysms = CMpbysmsIn;
          this.CMpbytgk = CMpbytgkIn;
          this.CMnamsms = CMnamsmsIn;
          this.CMnamtgk = CMnamtgkIn;
          this.CMnbysms = CMnbysmsIn;
          this.CMnbytgk = CMnbytgkIn;
          this.CMbamsms = CMbamsmsIn;
          this.CMbamtgk = CMbamtgkIn;
          this.CMbbysms = CMbbysmsIn;
          this.CMbbytgk = CMbbytgkIn;
          this.CMpbksms = CMpbksmsIn;
          this.CMpbktgk = CMpbktgkIn;
          this.CMnbksms = CMnbksmsIn;
          this.CMnbktgk = CMnbktgkIn;
          this.CMbbksms = CMbbksmsIn;
          this.CMbbktgk = CMbbktgkIn;
          this.CMplebh1 = CMplebh1In;
          this.CMblebh1 = CMblebh1In;
          this.CMnlebh1 = CMnlebh1In;
    }


    /** 
     * hasEqualMapping-method will compare two HVcmk1 instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(HVcmk1 valueObject) {

          if (this.CMpamsms == null) {
                    if (valueObject.getCMpamsms() != null)
                           return(false);
          } else if (!this.CMpamsms.equals(valueObject.getCMpamsms())) {
                    return(false);
          }
          if (this.CMpamtgk == null) {
                    if (valueObject.getCMpamtgk() != null)
                           return(false);
          } else if (!this.CMpamtgk.equals(valueObject.getCMpamtgk())) {
                    return(false);
          }
          if (this.CMpbysms == null) {
                    if (valueObject.getCMpbysms() != null)
                           return(false);
          } else if (!this.CMpbysms.equals(valueObject.getCMpbysms())) {
                    return(false);
          }
          if (this.CMpbytgk == null) {
                    if (valueObject.getCMpbytgk() != null)
                           return(false);
          } else if (!this.CMpbytgk.equals(valueObject.getCMpbytgk())) {
                    return(false);
          }
          if (this.CMnamsms == null) {
                    if (valueObject.getCMnamsms() != null)
                           return(false);
          } else if (!this.CMnamsms.equals(valueObject.getCMnamsms())) {
                    return(false);
          }
          if (this.CMnamtgk == null) {
                    if (valueObject.getCMnamtgk() != null)
                           return(false);
          } else if (!this.CMnamtgk.equals(valueObject.getCMnamtgk())) {
                    return(false);
          }
          if (this.CMnbysms == null) {
                    if (valueObject.getCMnbysms() != null)
                           return(false);
          } else if (!this.CMnbysms.equals(valueObject.getCMnbysms())) {
                    return(false);
          }
          if (this.CMnbytgk == null) {
                    if (valueObject.getCMnbytgk() != null)
                           return(false);
          } else if (!this.CMnbytgk.equals(valueObject.getCMnbytgk())) {
                    return(false);
          }
          if (this.CMbamsms == null) {
                    if (valueObject.getCMbamsms() != null)
                           return(false);
          } else if (!this.CMbamsms.equals(valueObject.getCMbamsms())) {
                    return(false);
          }
          if (this.CMbamtgk == null) {
                    if (valueObject.getCMbamtgk() != null)
                           return(false);
          } else if (!this.CMbamtgk.equals(valueObject.getCMbamtgk())) {
                    return(false);
          }
          if (this.CMbbysms == null) {
                    if (valueObject.getCMbbysms() != null)
                           return(false);
          } else if (!this.CMbbysms.equals(valueObject.getCMbbysms())) {
                    return(false);
          }
          if (this.CMbbytgk == null) {
                    if (valueObject.getCMbbytgk() != null)
                           return(false);
          } else if (!this.CMbbytgk.equals(valueObject.getCMbbytgk())) {
                    return(false);
          }
          if (this.CMpbksms == null) {
                    if (valueObject.getCMpbksms() != null)
                           return(false);
          } else if (!this.CMpbksms.equals(valueObject.getCMpbksms())) {
                    return(false);
          }
          if (this.CMpbktgk == null) {
                    if (valueObject.getCMpbktgk() != null)
                           return(false);
          } else if (!this.CMpbktgk.equals(valueObject.getCMpbktgk())) {
                    return(false);
          }
          if (this.CMnbksms == null) {
                    if (valueObject.getCMnbksms() != null)
                           return(false);
          } else if (!this.CMnbksms.equals(valueObject.getCMnbksms())) {
                    return(false);
          }
          if (this.CMnbktgk == null) {
                    if (valueObject.getCMnbktgk() != null)
                           return(false);
          } else if (!this.CMnbktgk.equals(valueObject.getCMnbktgk())) {
                    return(false);
          }
          if (this.CMbbksms == null) {
                    if (valueObject.getCMbbksms() != null)
                           return(false);
          } else if (!this.CMbbksms.equals(valueObject.getCMbbksms())) {
                    return(false);
          }
          if (this.CMbbktgk == null) {
                    if (valueObject.getCMbbktgk() != null)
                           return(false);
          } else if (!this.CMbbktgk.equals(valueObject.getCMbbktgk())) {
                    return(false);
          }
          if (this.CMplebh1 == null) {
                    if (valueObject.getCMplebh1() != null)
                           return(false);
          } else if (!this.CMplebh1.equals(valueObject.getCMplebh1())) {
                    return(false);
          }
          if (this.CMblebh1 == null) {
                    if (valueObject.getCMblebh1() != null)
                           return(false);
          } else if (!this.CMblebh1.equals(valueObject.getCMblebh1())) {
                    return(false);
          }
          if (this.CMnlebh1 == null) {
                    if (valueObject.getCMnlebh1() != null)
                           return(false);
          } else if (!this.CMnlebh1.equals(valueObject.getCMnlebh1())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass HVcmk1, mapping to table mtkn.HVCMK1, MTKN.hvcmk2, MTKN.hvcmk3,MTKN.HVCMK4,mtkn.hvcmk5\n");
        out.append("Persistent attributes: \n"); 
        out.append("CMpamsms = " + this.CMpamsms + "\n"); 
        out.append("CMpamtgk = " + this.CMpamtgk + "\n"); 
        out.append("CMpbysms = " + this.CMpbysms + "\n"); 
        out.append("CMpbytgk = " + this.CMpbytgk + "\n"); 
        out.append("CMnamsms = " + this.CMnamsms + "\n"); 
        out.append("CMnamtgk = " + this.CMnamtgk + "\n"); 
        out.append("CMnbysms = " + this.CMnbysms + "\n"); 
        out.append("CMnbytgk = " + this.CMnbytgk + "\n"); 
        out.append("CMbamsms = " + this.CMbamsms + "\n"); 
        out.append("CMbamtgk = " + this.CMbamtgk + "\n"); 
        out.append("CMbbysms = " + this.CMbbysms + "\n"); 
        out.append("CMbbytgk = " + this.CMbbytgk + "\n"); 
        out.append("CMpbksms = " + this.CMpbksms + "\n"); 
        out.append("CMpbktgk = " + this.CMpbktgk + "\n"); 
        out.append("CMnbksms = " + this.CMnbksms + "\n"); 
        out.append("CMnbktgk = " + this.CMnbktgk + "\n"); 
        out.append("CMbbksms = " + this.CMbbksms + "\n"); 
        out.append("CMbbktgk = " + this.CMbbktgk + "\n"); 
        out.append("CMplebh1 = " + this.CMplebh1 + "\n"); 
        out.append("CMblebh1 = " + this.CMblebh1 + "\n"); 
        out.append("CMnlebh1 = " + this.CMnlebh1 + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        HVcmk1 cloned = new HVcmk1();

        if (this.CMpamsms != null)
             cloned.setCMpamsms(new String(this.CMpamsms)); 
        if (this.CMpamtgk != null)
             cloned.setCMpamtgk(new String(this.CMpamtgk)); 
        if (this.CMpbysms != null)
             cloned.setCMpbysms(new String(this.CMpbysms)); 
        if (this.CMpbytgk != null)
             cloned.setCMpbytgk(new String(this.CMpbytgk)); 
        if (this.CMnamsms != null)
             cloned.setCMnamsms(new String(this.CMnamsms)); 
        if (this.CMnamtgk != null)
             cloned.setCMnamtgk(new String(this.CMnamtgk)); 
        if (this.CMnbysms != null)
             cloned.setCMnbysms(new String(this.CMnbysms)); 
        if (this.CMnbytgk != null)
             cloned.setCMnbytgk(new String(this.CMnbytgk)); 
        if (this.CMbamsms != null)
             cloned.setCMbamsms(new String(this.CMbamsms)); 
        if (this.CMbamtgk != null)
             cloned.setCMbamtgk(new String(this.CMbamtgk)); 
        if (this.CMbbysms != null)
             cloned.setCMbbysms(new String(this.CMbbysms)); 
        if (this.CMbbytgk != null)
             cloned.setCMbbytgk(new String(this.CMbbytgk)); 
        if (this.CMpbksms != null)
             cloned.setCMpbksms(new String(this.CMpbksms)); 
        if (this.CMpbktgk != null)
             cloned.setCMpbktgk(new String(this.CMpbktgk)); 
        if (this.CMnbksms != null)
             cloned.setCMnbksms(new String(this.CMnbksms)); 
        if (this.CMnbktgk != null)
             cloned.setCMnbktgk(new String(this.CMnbktgk)); 
        if (this.CMbbksms != null)
             cloned.setCMbbksms(new String(this.CMbbksms)); 
        if (this.CMbbktgk != null)
             cloned.setCMbbktgk(new String(this.CMbbktgk)); 
        if (this.CMplebh1 != null)
             cloned.setCMplebh1(new String(this.CMplebh1)); 
        if (this.CMblebh1 != null)
             cloned.setCMblebh1(new String(this.CMblebh1)); 
        if (this.CMnlebh1 != null)
             cloned.setCMnlebh1(new String(this.CMnlebh1)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}