package com.epbt2.mtkn.tanya.dao;

import com.epbt2.util.NotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;





 /**
  * HVctcr Data Access Object (DAO).
  * This class contains all database handling that is needed to 
  * permanently store and retrieve HVctcr object instances. 
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HVctcrDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public HVctcr createValueObject() {
          return new HVctcr();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public HVctcr getObject(Connection conn, String pegAkaun) throws NotFoundException, SQLException {

          HVctcr valueObject = createValueObject();
          valueObject.setPegAkaun(pegAkaun);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, HVctcr valueObject) throws NotFoundException, SQLException {

          if (valueObject.getPegAkaun() == null) {
               //System.out.println("Can not select without Primary-Key!");
               throw new NotFoundException("Can not select without Primary-Key!");
          }

          String sql = "SELECT * FROM mtkn.hvctcr WHERE (PEG_AKAUN = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setString(1, valueObject.getPegAkaun()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM mtkn.hvctcr ORDER BY PEG_AKAUN ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, HVctcr valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO mtkn.hvctcr ( PEG_AKAUN, PEG_DIGIT, PEG_JLKOD, "
               + "PEG_THKOD, PEG_HTKOD, PEG_JPKOD, "
               + "PEG_BGKOD, PEG_STKOD, PEG_NOLOT, "
               + "PEG_BLLOT, PEG_NOMPT, PEG_PELAN, "
               + "PEG_ADPG1, PEG_TKHOC, PEG_TKHTK, "
               + "PEG_TKHPL, PEG_NILTH, PEG_BILPK, "
               + "PEG_LSBGN, PEG_LSTNH, PEG_RJFIL, "
               + "PEG_RJMMK, PEG_STATF, PEG_OLDAC, "
               + "PEG_STATK, PEG_STCBK, PEG_ONAMA, "
               + "PEG_LSANS, PEG_ADPG2, PEG_AKLSN, "
               + "PEG_AKSWN, PEG_AKPBG, PEG_SMPAH, "
               + "PEG_CODEX, PEG_CODEY, PEG_DISKN, "
               + "PMK_AKAUN, PMK_PLGID, PMK_NMBIL, "
               + "PMK_BLPMK, PMK_HKMLK, PMK_KDANS, "
               + "PMK_KDEXP, PMK_PRTUS, PMK_RUJMJ, "
               + "PMK_JILID, PMK_STATF, PMK_STANG, "
               + "PMK_KPPEK, PMK_AMTID, PMK_ONAMA, "
               + "JLN_KWKOD, JLN_KNAMA, JLN_JLKOD, "
               + "JLN_JNAMA, JLN_POSKD, JLN_NEGRI, "
               + "JLN_PSKOD, KAW_KWKOD, KAW_HTKOD, "
               + "KAW_KADAR, JPK_JPKOD, JPK_ITKOD, "
               + "JPK_JNAMA, JPK_STCBK, PEG_WSTATF, "
               + "PMK_WSTATF, PMK_WKDANS, PMK_WKDEXP, "
               + "PEG_TKSIR, TKN_TKSR1, TKN_TKSR2, "
               + "TKN_ADPG1, TKN_ADPG2, TKN_ADPG3, "
               + "TKN_ADPG4, TKN_NOAKN, TKN_BCODE, "
               + "PVD_PLGID, PVD_JENPG, PVD_AMTID, "
               + "PVD_MODIN, PVD_AKAUN, PVD_PNAMA, "
               + "PVD_ALMT1, PVD_ALMT2, PVD_ALMT3, "
               + "PVD_ALMT4, PVD_ALMT5, PVD_OVSEA, "
               + "PVD_EMAIL, PVD_NOTEL, PVD_NOMHP, "
               + "PVD_NOFAX, PVD_WBNGSA, PVD_WKBGSA, "
               + "PVD_ALMT0, HRT_HNAMA, TNH_TNAMA, "
               + "BGN_BNAMA, STB_SNAMA, KWS_KWKOD, "
               + "KWS_KNAMA, KWS_MKKOD, MKM_MKKOD, "
               + "MKM_MNAMA, PEG_HTANG, PYT_STATS, "
               + "PYT_TGKCT, PYT_TGKDD, PYT_TGKNE, "
               + "PYT_TGKWF, PYT_TGKND, PYT_CTSIR, "
               + "PYT_DENDA, PYT_NOTIS, PYT_WARAN, "
               + "PYT_AMNOD, PYT_BYTCT, PYT_BYTDD, "
               + "PYT_BYTNE, PYT_BYTWF, PYT_BYTOD, "
               + "PYT_BYSCT, PYT_BYSDD, PYT_BYSNE, "
               + "PYT_BYSWF, PYT_BYSOD, PYT_TMPOH) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setString(1, valueObject.getPegAkaun()); 
               stmt.setString(2, valueObject.getPegDigit()); 
               stmt.setString(3, valueObject.getPegJlkod()); 
               stmt.setString(4, valueObject.getPegThkod()); 
               stmt.setString(5, valueObject.getPegHtkod()); 
               stmt.setString(6, valueObject.getPegJpkod()); 
               stmt.setString(7, valueObject.getPegBgkod()); 
               stmt.setString(8, valueObject.getPegStkod()); 
               stmt.setString(9, valueObject.getPegNolot()); 
               stmt.setString(10, valueObject.getPegBllot()); 
               stmt.setString(11, valueObject.getPegNompt()); 
               stmt.setString(12, valueObject.getPegPelan()); 
               stmt.setString(13, valueObject.getPegAdpg1()); 
               stmt.setString(14, valueObject.getPegTkhoc()); 
               stmt.setString(15, valueObject.getPegTkhtk()); 
               stmt.setString(16, valueObject.getPegTkhpl()); 
               stmt.setString(17, valueObject.getPegNilth()); 
               stmt.setString(18, valueObject.getPegBilpk()); 
               stmt.setString(19, valueObject.getPegLsbgn()); 
               stmt.setString(20, valueObject.getPegLstnh()); 
               stmt.setString(21, valueObject.getPegRjfil()); 
               stmt.setString(22, valueObject.getPegRjmmk()); 
               stmt.setString(23, valueObject.getPegStatf()); 
               stmt.setString(24, valueObject.getPegOldac()); 
               stmt.setString(25, valueObject.getPegStatk()); 
               stmt.setString(26, valueObject.getPegStcbk()); 
               stmt.setString(27, valueObject.getPegOnama()); 
               stmt.setString(28, valueObject.getPegLsans()); 
               stmt.setString(29, valueObject.getPegAdpg2()); 
               stmt.setString(30, valueObject.getPegAklsn()); 
               stmt.setString(31, valueObject.getPegAkswn()); 
               stmt.setString(32, valueObject.getPegAkpbg()); 
               stmt.setString(33, valueObject.getPegSmpah()); 
               stmt.setString(34, valueObject.getPegCodex()); 
               stmt.setString(35, valueObject.getPegCodey()); 
               stmt.setString(36, valueObject.getPegDiskn()); 
               stmt.setString(37, valueObject.getPmkAkaun()); 
               stmt.setString(38, valueObject.getPmkPlgid()); 
               stmt.setString(39, valueObject.getPmkNmbil()); 
               stmt.setString(40, valueObject.getPmkBlpmk()); 
               stmt.setString(41, valueObject.getPmkHkmlk()); 
               stmt.setString(42, valueObject.getPmkKdans()); 
               stmt.setString(43, valueObject.getPmkKdexp()); 
               stmt.setString(44, valueObject.getPmkPrtus()); 
               stmt.setString(45, valueObject.getPmkRujmj()); 
               stmt.setString(46, valueObject.getPmkJilid()); 
               stmt.setString(47, valueObject.getPmkStatf()); 
               stmt.setString(48, valueObject.getPmkStang()); 
               stmt.setString(49, valueObject.getPmkKppek()); 
               stmt.setString(50, valueObject.getPmkAmtid()); 
               stmt.setString(51, valueObject.getPmkOnama()); 
               stmt.setString(52, valueObject.getJlnKwkod()); 
               stmt.setString(53, valueObject.getJlnKnama()); 
               stmt.setString(54, valueObject.getJlnJlkod()); 
               stmt.setString(55, valueObject.getJlnJnama()); 
               stmt.setString(56, valueObject.getJlnPoskd()); 
               stmt.setString(57, valueObject.getJlnNegri()); 
               stmt.setString(58, valueObject.getJlnPskod()); 
               stmt.setString(59, valueObject.getKawKwkod()); 
               stmt.setString(60, valueObject.getKawHtkod()); 
               stmt.setString(61, valueObject.getKawKadar()); 
               stmt.setString(62, valueObject.getJpkJpkod()); 
               stmt.setString(63, valueObject.getJpkItkod()); 
               stmt.setString(64, valueObject.getJpkJnama()); 
               stmt.setString(65, valueObject.getJpkStcbk()); 
               stmt.setString(66, valueObject.getPegWstatf()); 
               stmt.setString(67, valueObject.getPmkWstatf()); 
               stmt.setString(68, valueObject.getPmkWkdans()); 
               stmt.setString(69, valueObject.getPmkWkdexp()); 
               stmt.setString(70, valueObject.getPegTksir()); 
               stmt.setString(71, valueObject.getTknTksr1()); 
               stmt.setString(72, valueObject.getTknTksr2()); 
               stmt.setString(73, valueObject.getTknAdpg1()); 
               stmt.setString(74, valueObject.getTknAdpg2()); 
               stmt.setString(75, valueObject.getTknAdpg3()); 
               stmt.setString(76, valueObject.getTknAdpg4()); 
               stmt.setString(77, valueObject.getTknNoakn()); 
               stmt.setString(78, valueObject.getTknBcode()); 
               stmt.setString(79, valueObject.getPvdPlgid()); 
               stmt.setString(80, valueObject.getPvdJenpg()); 
               stmt.setString(81, valueObject.getPvdAmtid()); 
               stmt.setString(82, valueObject.getPvdModin()); 
               stmt.setString(83, valueObject.getPvdAkaun()); 
               stmt.setString(84, valueObject.getPvdPnama()); 
               stmt.setString(85, valueObject.getPvdAlmt1()); 
               stmt.setString(86, valueObject.getPvdAlmt2()); 
               stmt.setString(87, valueObject.getPvdAlmt3()); 
               stmt.setString(88, valueObject.getPvdAlmt4()); 
               stmt.setString(89, valueObject.getPvdAlmt5()); 
               stmt.setString(90, valueObject.getPvdOvsea()); 
               stmt.setString(91, valueObject.getPvdEmail()); 
               stmt.setString(92, valueObject.getPvdNotel()); 
               stmt.setString(93, valueObject.getPvdNomhp()); 
               stmt.setString(94, valueObject.getPvdNofax()); 
               stmt.setString(95, valueObject.getPvdWbngsa()); 
               stmt.setString(96, valueObject.getPvdWkbgsa()); 
               stmt.setString(97, valueObject.getPvdAlmt0()); 
               stmt.setString(98, valueObject.getHrtHnama()); 
               stmt.setString(99, valueObject.getTnhTnama()); 
               stmt.setString(100, valueObject.getBgnBnama()); 
               stmt.setString(101, valueObject.getStbSnama()); 
               stmt.setString(102, valueObject.getKwsKwkod()); 
               stmt.setString(103, valueObject.getKwsKnama()); 
               stmt.setString(104, valueObject.getKwsMkkod()); 
               stmt.setString(105, valueObject.getMkmMkkod()); 
               stmt.setString(106, valueObject.getMkmMnama()); 
               stmt.setString(107, valueObject.getPegHtang()); 
               stmt.setString(108, valueObject.getPytStats()); 
               stmt.setString(109, valueObject.getPytTgkct()); 
               stmt.setString(110, valueObject.getPytTgkdd()); 
               stmt.setString(111, valueObject.getPytTgkne()); 
               stmt.setString(112, valueObject.getPytTgkwf()); 
               stmt.setString(113, valueObject.getPytTgknd()); 
               stmt.setString(114, valueObject.getPytCtsir()); 
               stmt.setString(115, valueObject.getPytDenda()); 
               stmt.setString(116, valueObject.getPytNotis()); 
               stmt.setString(117, valueObject.getPytWaran()); 
               stmt.setString(118, valueObject.getPytAmnod()); 
               stmt.setString(119, valueObject.getPytBytct()); 
               stmt.setString(120, valueObject.getPytBytdd()); 
               stmt.setString(121, valueObject.getPytBytne()); 
               stmt.setString(122, valueObject.getPytBytwf()); 
               stmt.setString(123, valueObject.getPytBytod()); 
               stmt.setString(124, valueObject.getPytBysct()); 
               stmt.setString(125, valueObject.getPytBysdd()); 
               stmt.setString(126, valueObject.getPytBysne()); 
               stmt.setString(127, valueObject.getPytByswf()); 
               stmt.setString(128, valueObject.getPytBysod()); 
               stmt.setString(129, valueObject.getPytTmpoh()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, HVctcr valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE mtkn.hvctcr SET PEG_DIGIT = ?, PEG_JLKOD = ?, PEG_THKOD = ?, "
               + "PEG_HTKOD = ?, PEG_JPKOD = ?, PEG_BGKOD = ?, "
               + "PEG_STKOD = ?, PEG_NOLOT = ?, PEG_BLLOT = ?, "
               + "PEG_NOMPT = ?, PEG_PELAN = ?, PEG_ADPG1 = ?, "
               + "PEG_TKHOC = ?, PEG_TKHTK = ?, PEG_TKHPL = ?, "
               + "PEG_NILTH = ?, PEG_BILPK = ?, PEG_LSBGN = ?, "
               + "PEG_LSTNH = ?, PEG_RJFIL = ?, PEG_RJMMK = ?, "
               + "PEG_STATF = ?, PEG_OLDAC = ?, PEG_STATK = ?, "
               + "PEG_STCBK = ?, PEG_ONAMA = ?, PEG_LSANS = ?, "
               + "PEG_ADPG2 = ?, PEG_AKLSN = ?, PEG_AKSWN = ?, "
               + "PEG_AKPBG = ?, PEG_SMPAH = ?, PEG_CODEX = ?, "
               + "PEG_CODEY = ?, PEG_DISKN = ?, PMK_AKAUN = ?, "
               + "PMK_PLGID = ?, PMK_NMBIL = ?, PMK_BLPMK = ?, "
               + "PMK_HKMLK = ?, PMK_KDANS = ?, PMK_KDEXP = ?, "
               + "PMK_PRTUS = ?, PMK_RUJMJ = ?, PMK_JILID = ?, "
               + "PMK_STATF = ?, PMK_STANG = ?, PMK_KPPEK = ?, "
               + "PMK_AMTID = ?, PMK_ONAMA = ?, JLN_KWKOD = ?, "
               + "JLN_KNAMA = ?, JLN_JLKOD = ?, JLN_JNAMA = ?, "
               + "JLN_POSKD = ?, JLN_NEGRI = ?, JLN_PSKOD = ?, "
               + "KAW_KWKOD = ?, KAW_HTKOD = ?, KAW_KADAR = ?, "
               + "JPK_JPKOD = ?, JPK_ITKOD = ?, JPK_JNAMA = ?, "
               + "JPK_STCBK = ?, PEG_WSTATF = ?, PMK_WSTATF = ?, "
               + "PMK_WKDANS = ?, PMK_WKDEXP = ?, PEG_TKSIR = ?, "
               + "TKN_TKSR1 = ?, TKN_TKSR2 = ?, TKN_ADPG1 = ?, "
               + "TKN_ADPG2 = ?, TKN_ADPG3 = ?, TKN_ADPG4 = ?, "
               + "TKN_NOAKN = ?, TKN_BCODE = ?, PVD_PLGID = ?, "
               + "PVD_JENPG = ?, PVD_AMTID = ?, PVD_MODIN = ?, "
               + "PVD_AKAUN = ?, PVD_PNAMA = ?, PVD_ALMT1 = ?, "
               + "PVD_ALMT2 = ?, PVD_ALMT3 = ?, PVD_ALMT4 = ?, "
               + "PVD_ALMT5 = ?, PVD_OVSEA = ?, PVD_EMAIL = ?, "
               + "PVD_NOTEL = ?, PVD_NOMHP = ?, PVD_NOFAX = ?, "
               + "PVD_WBNGSA = ?, PVD_WKBGSA = ?, PVD_ALMT0 = ?, "
               + "HRT_HNAMA = ?, TNH_TNAMA = ?, BGN_BNAMA = ?, "
               + "STB_SNAMA = ?, KWS_KWKOD = ?, KWS_KNAMA = ?, "
               + "KWS_MKKOD = ?, MKM_MKKOD = ?, MKM_MNAMA = ?, "
               + "PEG_HTANG = ?, PYT_STATS = ?, PYT_TGKCT = ?, "
               + "PYT_TGKDD = ?, PYT_TGKNE = ?, PYT_TGKWF = ?, "
               + "PYT_TGKND = ?, PYT_CTSIR = ?, PYT_DENDA = ?, "
               + "PYT_NOTIS = ?, PYT_WARAN = ?, PYT_AMNOD = ?, "
               + "PYT_BYTCT = ?, PYT_BYTDD = ?, PYT_BYTNE = ?, "
               + "PYT_BYTWF = ?, PYT_BYTOD = ?, PYT_BYSCT = ?, "
               + "PYT_BYSDD = ?, PYT_BYSNE = ?, PYT_BYSWF = ?, "
               + "PYT_BYSOD = ?, PYT_TMPOH = ? WHERE (PEG_AKAUN = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getPegDigit()); 
              stmt.setString(2, valueObject.getPegJlkod()); 
              stmt.setString(3, valueObject.getPegThkod()); 
              stmt.setString(4, valueObject.getPegHtkod()); 
              stmt.setString(5, valueObject.getPegJpkod()); 
              stmt.setString(6, valueObject.getPegBgkod()); 
              stmt.setString(7, valueObject.getPegStkod()); 
              stmt.setString(8, valueObject.getPegNolot()); 
              stmt.setString(9, valueObject.getPegBllot()); 
              stmt.setString(10, valueObject.getPegNompt()); 
              stmt.setString(11, valueObject.getPegPelan()); 
              stmt.setString(12, valueObject.getPegAdpg1()); 
              stmt.setString(13, valueObject.getPegTkhoc()); 
              stmt.setString(14, valueObject.getPegTkhtk()); 
              stmt.setString(15, valueObject.getPegTkhpl()); 
              stmt.setString(16, valueObject.getPegNilth()); 
              stmt.setString(17, valueObject.getPegBilpk()); 
              stmt.setString(18, valueObject.getPegLsbgn()); 
              stmt.setString(19, valueObject.getPegLstnh()); 
              stmt.setString(20, valueObject.getPegRjfil()); 
              stmt.setString(21, valueObject.getPegRjmmk()); 
              stmt.setString(22, valueObject.getPegStatf()); 
              stmt.setString(23, valueObject.getPegOldac()); 
              stmt.setString(24, valueObject.getPegStatk()); 
              stmt.setString(25, valueObject.getPegStcbk()); 
              stmt.setString(26, valueObject.getPegOnama()); 
              stmt.setString(27, valueObject.getPegLsans()); 
              stmt.setString(28, valueObject.getPegAdpg2()); 
              stmt.setString(29, valueObject.getPegAklsn()); 
              stmt.setString(30, valueObject.getPegAkswn()); 
              stmt.setString(31, valueObject.getPegAkpbg()); 
              stmt.setString(32, valueObject.getPegSmpah()); 
              stmt.setString(33, valueObject.getPegCodex()); 
              stmt.setString(34, valueObject.getPegCodey()); 
              stmt.setString(35, valueObject.getPegDiskn()); 
              stmt.setString(36, valueObject.getPmkAkaun()); 
              stmt.setString(37, valueObject.getPmkPlgid()); 
              stmt.setString(38, valueObject.getPmkNmbil()); 
              stmt.setString(39, valueObject.getPmkBlpmk()); 
              stmt.setString(40, valueObject.getPmkHkmlk()); 
              stmt.setString(41, valueObject.getPmkKdans()); 
              stmt.setString(42, valueObject.getPmkKdexp()); 
              stmt.setString(43, valueObject.getPmkPrtus()); 
              stmt.setString(44, valueObject.getPmkRujmj()); 
              stmt.setString(45, valueObject.getPmkJilid()); 
              stmt.setString(46, valueObject.getPmkStatf()); 
              stmt.setString(47, valueObject.getPmkStang()); 
              stmt.setString(48, valueObject.getPmkKppek()); 
              stmt.setString(49, valueObject.getPmkAmtid()); 
              stmt.setString(50, valueObject.getPmkOnama()); 
              stmt.setString(51, valueObject.getJlnKwkod()); 
              stmt.setString(52, valueObject.getJlnKnama()); 
              stmt.setString(53, valueObject.getJlnJlkod()); 
              stmt.setString(54, valueObject.getJlnJnama()); 
              stmt.setString(55, valueObject.getJlnPoskd()); 
              stmt.setString(56, valueObject.getJlnNegri()); 
              stmt.setString(57, valueObject.getJlnPskod()); 
              stmt.setString(58, valueObject.getKawKwkod()); 
              stmt.setString(59, valueObject.getKawHtkod()); 
              stmt.setString(60, valueObject.getKawKadar()); 
              stmt.setString(61, valueObject.getJpkJpkod()); 
              stmt.setString(62, valueObject.getJpkItkod()); 
              stmt.setString(63, valueObject.getJpkJnama()); 
              stmt.setString(64, valueObject.getJpkStcbk()); 
              stmt.setString(65, valueObject.getPegWstatf()); 
              stmt.setString(66, valueObject.getPmkWstatf()); 
              stmt.setString(67, valueObject.getPmkWkdans()); 
              stmt.setString(68, valueObject.getPmkWkdexp()); 
              stmt.setString(69, valueObject.getPegTksir()); 
              stmt.setString(70, valueObject.getTknTksr1()); 
              stmt.setString(71, valueObject.getTknTksr2()); 
              stmt.setString(72, valueObject.getTknAdpg1()); 
              stmt.setString(73, valueObject.getTknAdpg2()); 
              stmt.setString(74, valueObject.getTknAdpg3()); 
              stmt.setString(75, valueObject.getTknAdpg4()); 
              stmt.setString(76, valueObject.getTknNoakn()); 
              stmt.setString(77, valueObject.getTknBcode()); 
              stmt.setString(78, valueObject.getPvdPlgid()); 
              stmt.setString(79, valueObject.getPvdJenpg()); 
              stmt.setString(80, valueObject.getPvdAmtid()); 
              stmt.setString(81, valueObject.getPvdModin()); 
              stmt.setString(82, valueObject.getPvdAkaun()); 
              stmt.setString(83, valueObject.getPvdPnama()); 
              stmt.setString(84, valueObject.getPvdAlmt1()); 
              stmt.setString(85, valueObject.getPvdAlmt2()); 
              stmt.setString(86, valueObject.getPvdAlmt3()); 
              stmt.setString(87, valueObject.getPvdAlmt4()); 
              stmt.setString(88, valueObject.getPvdAlmt5()); 
              stmt.setString(89, valueObject.getPvdOvsea()); 
              stmt.setString(90, valueObject.getPvdEmail()); 
              stmt.setString(91, valueObject.getPvdNotel()); 
              stmt.setString(92, valueObject.getPvdNomhp()); 
              stmt.setString(93, valueObject.getPvdNofax()); 
              stmt.setString(94, valueObject.getPvdWbngsa()); 
              stmt.setString(95, valueObject.getPvdWkbgsa()); 
              stmt.setString(96, valueObject.getPvdAlmt0()); 
              stmt.setString(97, valueObject.getHrtHnama()); 
              stmt.setString(98, valueObject.getTnhTnama()); 
              stmt.setString(99, valueObject.getBgnBnama()); 
              stmt.setString(100, valueObject.getStbSnama()); 
              stmt.setString(101, valueObject.getKwsKwkod()); 
              stmt.setString(102, valueObject.getKwsKnama()); 
              stmt.setString(103, valueObject.getKwsMkkod()); 
              stmt.setString(104, valueObject.getMkmMkkod()); 
              stmt.setString(105, valueObject.getMkmMnama()); 
              stmt.setString(106, valueObject.getPegHtang()); 
              stmt.setString(107, valueObject.getPytStats()); 
              stmt.setString(108, valueObject.getPytTgkct()); 
              stmt.setString(109, valueObject.getPytTgkdd()); 
              stmt.setString(110, valueObject.getPytTgkne()); 
              stmt.setString(111, valueObject.getPytTgkwf()); 
              stmt.setString(112, valueObject.getPytTgknd()); 
              stmt.setString(113, valueObject.getPytCtsir()); 
              stmt.setString(114, valueObject.getPytDenda()); 
              stmt.setString(115, valueObject.getPytNotis()); 
              stmt.setString(116, valueObject.getPytWaran()); 
              stmt.setString(117, valueObject.getPytAmnod()); 
              stmt.setString(118, valueObject.getPytBytct()); 
              stmt.setString(119, valueObject.getPytBytdd()); 
              stmt.setString(120, valueObject.getPytBytne()); 
              stmt.setString(121, valueObject.getPytBytwf()); 
              stmt.setString(122, valueObject.getPytBytod()); 
              stmt.setString(123, valueObject.getPytBysct()); 
              stmt.setString(124, valueObject.getPytBysdd()); 
              stmt.setString(125, valueObject.getPytBysne()); 
              stmt.setString(126, valueObject.getPytByswf()); 
              stmt.setString(127, valueObject.getPytBysod()); 
              stmt.setString(128, valueObject.getPytTmpoh()); 

              stmt.setString(129, valueObject.getPegAkaun()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, HVctcr valueObject) 
          throws NotFoundException, SQLException {

          if (valueObject.getPegAkaun() == null) {
               //System.out.println("Can not delete without Primary-Key!");
               throw new NotFoundException("Can not delete without Primary-Key!");
          }

          String sql = "DELETE FROM mtkn.hvctcr WHERE (PEG_AKAUN = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getPegAkaun()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM mtkn.hvctcr";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM mtkn.hvctcr";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, HVctcr valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM mtkn.hvctcr WHERE 1=1 ");

          if (valueObject.getPegAkaun() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_AKAUN LIKE '").append(valueObject.getPegAkaun()).append("%' ");
          }

          if (valueObject.getPegDigit() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_DIGIT LIKE '").append(valueObject.getPegDigit()).append("%' ");
          }

          if (valueObject.getPegJlkod() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_JLKOD LIKE '").append(valueObject.getPegJlkod()).append("%' ");
          }

          if (valueObject.getPegThkod() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_THKOD LIKE '").append(valueObject.getPegThkod()).append("%' ");
          }

          if (valueObject.getPegHtkod() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_HTKOD LIKE '").append(valueObject.getPegHtkod()).append("%' ");
          }

          if (valueObject.getPegJpkod() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_JPKOD LIKE '").append(valueObject.getPegJpkod()).append("%' ");
          }

          if (valueObject.getPegBgkod() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_BGKOD LIKE '").append(valueObject.getPegBgkod()).append("%' ");
          }

          if (valueObject.getPegStkod() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_STKOD LIKE '").append(valueObject.getPegStkod()).append("%' ");
          }

          if (valueObject.getPegNolot() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_NOLOT LIKE '").append(valueObject.getPegNolot()).append("%' ");
          }

          if (valueObject.getPegBllot() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_BLLOT LIKE '").append(valueObject.getPegBllot()).append("%' ");
          }

          if (valueObject.getPegNompt() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_NOMPT LIKE '").append(valueObject.getPegNompt()).append("%' ");
          }

          if (valueObject.getPegPelan() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_PELAN LIKE '").append(valueObject.getPegPelan()).append("%' ");
          }

          if (valueObject.getPegAdpg1() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_ADPG1 LIKE '").append(valueObject.getPegAdpg1()).append("%' ");
          }

          if (valueObject.getPegTkhoc() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_TKHOC LIKE '").append(valueObject.getPegTkhoc()).append("%' ");
          }

          if (valueObject.getPegTkhtk() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_TKHTK LIKE '").append(valueObject.getPegTkhtk()).append("%' ");
          }

          if (valueObject.getPegTkhpl() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_TKHPL LIKE '").append(valueObject.getPegTkhpl()).append("%' ");
          }

          if (valueObject.getPegNilth() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_NILTH LIKE '").append(valueObject.getPegNilth()).append("%' ");
          }

          if (valueObject.getPegBilpk() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_BILPK LIKE '").append(valueObject.getPegBilpk()).append("%' ");
          }

          if (valueObject.getPegLsbgn() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_LSBGN LIKE '").append(valueObject.getPegLsbgn()).append("%' ");
          }

          if (valueObject.getPegLstnh() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_LSTNH LIKE '").append(valueObject.getPegLstnh()).append("%' ");
          }

          if (valueObject.getPegRjfil() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_RJFIL LIKE '").append(valueObject.getPegRjfil()).append("%' ");
          }

          if (valueObject.getPegRjmmk() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_RJMMK LIKE '").append(valueObject.getPegRjmmk()).append("%' ");
          }

          if (valueObject.getPegStatf() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_STATF LIKE '").append(valueObject.getPegStatf()).append("%' ");
          }

          if (valueObject.getPegOldac() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_OLDAC LIKE '").append(valueObject.getPegOldac()).append("%' ");
          }

          if (valueObject.getPegStatk() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_STATK LIKE '").append(valueObject.getPegStatk()).append("%' ");
          }

          if (valueObject.getPegStcbk() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_STCBK LIKE '").append(valueObject.getPegStcbk()).append("%' ");
          }

          if (valueObject.getPegOnama() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_ONAMA LIKE '").append(valueObject.getPegOnama()).append("%' ");
          }

          if (valueObject.getPegLsans() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_LSANS LIKE '").append(valueObject.getPegLsans()).append("%' ");
          }

          if (valueObject.getPegAdpg2() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_ADPG2 LIKE '").append(valueObject.getPegAdpg2()).append("%' ");
          }

          if (valueObject.getPegAklsn() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_AKLSN LIKE '").append(valueObject.getPegAklsn()).append("%' ");
          }

          if (valueObject.getPegAkswn() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_AKSWN LIKE '").append(valueObject.getPegAkswn()).append("%' ");
          }

          if (valueObject.getPegAkpbg() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_AKPBG LIKE '").append(valueObject.getPegAkpbg()).append("%' ");
          }

          if (valueObject.getPegSmpah() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_SMPAH LIKE '").append(valueObject.getPegSmpah()).append("%' ");
          }

          if (valueObject.getPegCodex() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_CODEX LIKE '").append(valueObject.getPegCodex()).append("%' ");
          }

          if (valueObject.getPegCodey() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_CODEY LIKE '").append(valueObject.getPegCodey()).append("%' ");
          }

          if (valueObject.getPegDiskn() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_DISKN LIKE '").append(valueObject.getPegDiskn()).append("%' ");
          }

          if (valueObject.getPmkAkaun() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_AKAUN LIKE '").append(valueObject.getPmkAkaun()).append("%' ");
          }

          if (valueObject.getPmkPlgid() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_PLGID LIKE '").append(valueObject.getPmkPlgid()).append("%' ");
          }

          if (valueObject.getPmkNmbil() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_NMBIL LIKE '").append(valueObject.getPmkNmbil()).append("%' ");
          }

          if (valueObject.getPmkBlpmk() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_BLPMK LIKE '").append(valueObject.getPmkBlpmk()).append("%' ");
          }

          if (valueObject.getPmkHkmlk() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_HKMLK LIKE '").append(valueObject.getPmkHkmlk()).append("%' ");
          }

          if (valueObject.getPmkKdans() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_KDANS LIKE '").append(valueObject.getPmkKdans()).append("%' ");
          }

          if (valueObject.getPmkKdexp() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_KDEXP LIKE '").append(valueObject.getPmkKdexp()).append("%' ");
          }

          if (valueObject.getPmkPrtus() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_PRTUS LIKE '").append(valueObject.getPmkPrtus()).append("%' ");
          }

          if (valueObject.getPmkRujmj() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_RUJMJ LIKE '").append(valueObject.getPmkRujmj()).append("%' ");
          }

          if (valueObject.getPmkJilid() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_JILID LIKE '").append(valueObject.getPmkJilid()).append("%' ");
          }

          if (valueObject.getPmkStatf() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_STATF LIKE '").append(valueObject.getPmkStatf()).append("%' ");
          }

          if (valueObject.getPmkStang() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_STANG LIKE '").append(valueObject.getPmkStang()).append("%' ");
          }

          if (valueObject.getPmkKppek() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_KPPEK LIKE '").append(valueObject.getPmkKppek()).append("%' ");
          }

          if (valueObject.getPmkAmtid() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_AMTID LIKE '").append(valueObject.getPmkAmtid()).append("%' ");
          }

          if (valueObject.getPmkOnama() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_ONAMA LIKE '").append(valueObject.getPmkOnama()).append("%' ");
          }

          if (valueObject.getJlnKwkod() != null) {
              if (first) { first = false; }
              sql.append("AND JLN_KWKOD LIKE '").append(valueObject.getJlnKwkod()).append("%' ");
          }

          if (valueObject.getJlnKnama() != null) {
              if (first) { first = false; }
              sql.append("AND JLN_KNAMA LIKE '").append(valueObject.getJlnKnama()).append("%' ");
          }

          if (valueObject.getJlnJlkod() != null) {
              if (first) { first = false; }
              sql.append("AND JLN_JLKOD LIKE '").append(valueObject.getJlnJlkod()).append("%' ");
          }

          if (valueObject.getJlnJnama() != null) {
              if (first) { first = false; }
              sql.append("AND JLN_JNAMA LIKE '").append(valueObject.getJlnJnama()).append("%' ");
          }

          if (valueObject.getJlnPoskd() != null) {
              if (first) { first = false; }
              sql.append("AND JLN_POSKD LIKE '").append(valueObject.getJlnPoskd()).append("%' ");
          }

          if (valueObject.getJlnNegri() != null) {
              if (first) { first = false; }
              sql.append("AND JLN_NEGRI LIKE '").append(valueObject.getJlnNegri()).append("%' ");
          }

          if (valueObject.getJlnPskod() != null) {
              if (first) { first = false; }
              sql.append("AND JLN_PSKOD LIKE '").append(valueObject.getJlnPskod()).append("%' ");
          }

          if (valueObject.getKawKwkod() != null) {
              if (first) { first = false; }
              sql.append("AND KAW_KWKOD LIKE '").append(valueObject.getKawKwkod()).append("%' ");
          }

          if (valueObject.getKawHtkod() != null) {
              if (first) { first = false; }
              sql.append("AND KAW_HTKOD LIKE '").append(valueObject.getKawHtkod()).append("%' ");
          }

          if (valueObject.getKawKadar() != null) {
              if (first) { first = false; }
              sql.append("AND KAW_KADAR LIKE '").append(valueObject.getKawKadar()).append("%' ");
          }

          if (valueObject.getJpkJpkod() != null) {
              if (first) { first = false; }
              sql.append("AND JPK_JPKOD LIKE '").append(valueObject.getJpkJpkod()).append("%' ");
          }

          if (valueObject.getJpkItkod() != null) {
              if (first) { first = false; }
              sql.append("AND JPK_ITKOD LIKE '").append(valueObject.getJpkItkod()).append("%' ");
          }

          if (valueObject.getJpkJnama() != null) {
              if (first) { first = false; }
              sql.append("AND JPK_JNAMA LIKE '").append(valueObject.getJpkJnama()).append("%' ");
          }

          if (valueObject.getJpkStcbk() != null) {
              if (first) { first = false; }
              sql.append("AND JPK_STCBK LIKE '").append(valueObject.getJpkStcbk()).append("%' ");
          }

          if (valueObject.getPegWstatf() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_WSTATF LIKE '").append(valueObject.getPegWstatf()).append("%' ");
          }

          if (valueObject.getPmkWstatf() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_WSTATF LIKE '").append(valueObject.getPmkWstatf()).append("%' ");
          }

          if (valueObject.getPmkWkdans() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_WKDANS LIKE '").append(valueObject.getPmkWkdans()).append("%' ");
          }

          if (valueObject.getPmkWkdexp() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_WKDEXP LIKE '").append(valueObject.getPmkWkdexp()).append("%' ");
          }

          if (valueObject.getPegTksir() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_TKSIR LIKE '").append(valueObject.getPegTksir()).append("%' ");
          }

          if (valueObject.getTknTksr1() != null) {
              if (first) { first = false; }
              sql.append("AND TKN_TKSR1 LIKE '").append(valueObject.getTknTksr1()).append("%' ");
          }

          if (valueObject.getTknTksr2() != null) {
              if (first) { first = false; }
              sql.append("AND TKN_TKSR2 LIKE '").append(valueObject.getTknTksr2()).append("%' ");
          }

          if (valueObject.getTknAdpg1() != null) {
              if (first) { first = false; }
              sql.append("AND TKN_ADPG1 LIKE '").append(valueObject.getTknAdpg1()).append("%' ");
          }

          if (valueObject.getTknAdpg2() != null) {
              if (first) { first = false; }
              sql.append("AND TKN_ADPG2 LIKE '").append(valueObject.getTknAdpg2()).append("%' ");
          }

          if (valueObject.getTknAdpg3() != null) {
              if (first) { first = false; }
              sql.append("AND TKN_ADPG3 LIKE '").append(valueObject.getTknAdpg3()).append("%' ");
          }

          if (valueObject.getTknAdpg4() != null) {
              if (first) { first = false; }
              sql.append("AND TKN_ADPG4 LIKE '").append(valueObject.getTknAdpg4()).append("%' ");
          }

          if (valueObject.getTknNoakn() != null) {
              if (first) { first = false; }
              sql.append("AND TKN_NOAKN LIKE '").append(valueObject.getTknNoakn()).append("%' ");
          }

          if (valueObject.getTknBcode() != null) {
              if (first) { first = false; }
              sql.append("AND TKN_BCODE LIKE '").append(valueObject.getTknBcode()).append("%' ");
          }

          if (valueObject.getPvdPlgid() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_PLGID LIKE '").append(valueObject.getPvdPlgid()).append("%' ");
          }

          if (valueObject.getPvdJenpg() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_JENPG LIKE '").append(valueObject.getPvdJenpg()).append("%' ");
          }

          if (valueObject.getPvdAmtid() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_AMTID LIKE '").append(valueObject.getPvdAmtid()).append("%' ");
          }

          if (valueObject.getPvdModin() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_MODIN LIKE '").append(valueObject.getPvdModin()).append("%' ");
          }

          if (valueObject.getPvdAkaun() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_AKAUN LIKE '").append(valueObject.getPvdAkaun()).append("%' ");
          }

          if (valueObject.getPvdPnama() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_PNAMA LIKE '").append(valueObject.getPvdPnama()).append("%' ");
          }

          if (valueObject.getPvdAlmt1() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_ALMT1 LIKE '").append(valueObject.getPvdAlmt1()).append("%' ");
          }

          if (valueObject.getPvdAlmt2() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_ALMT2 LIKE '").append(valueObject.getPvdAlmt2()).append("%' ");
          }

          if (valueObject.getPvdAlmt3() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_ALMT3 LIKE '").append(valueObject.getPvdAlmt3()).append("%' ");
          }

          if (valueObject.getPvdAlmt4() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_ALMT4 LIKE '").append(valueObject.getPvdAlmt4()).append("%' ");
          }

          if (valueObject.getPvdAlmt5() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_ALMT5 LIKE '").append(valueObject.getPvdAlmt5()).append("%' ");
          }

          if (valueObject.getPvdOvsea() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_OVSEA LIKE '").append(valueObject.getPvdOvsea()).append("%' ");
          }

          if (valueObject.getPvdEmail() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_EMAIL LIKE '").append(valueObject.getPvdEmail()).append("%' ");
          }

          if (valueObject.getPvdNotel() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_NOTEL LIKE '").append(valueObject.getPvdNotel()).append("%' ");
          }

          if (valueObject.getPvdNomhp() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_NOMHP LIKE '").append(valueObject.getPvdNomhp()).append("%' ");
          }

          if (valueObject.getPvdNofax() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_NOFAX LIKE '").append(valueObject.getPvdNofax()).append("%' ");
          }

          if (valueObject.getPvdWbngsa() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_WBNGSA LIKE '").append(valueObject.getPvdWbngsa()).append("%' ");
          }

          if (valueObject.getPvdWkbgsa() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_WKBGSA LIKE '").append(valueObject.getPvdWkbgsa()).append("%' ");
          }

          if (valueObject.getPvdAlmt0() != null) {
              if (first) { first = false; }
              sql.append("AND PVD_ALMT0 LIKE '").append(valueObject.getPvdAlmt0()).append("%' ");
          }

          if (valueObject.getHrtHnama() != null) {
              if (first) { first = false; }
              sql.append("AND HRT_HNAMA LIKE '").append(valueObject.getHrtHnama()).append("%' ");
          }

          if (valueObject.getTnhTnama() != null) {
              if (first) { first = false; }
              sql.append("AND TNH_TNAMA LIKE '").append(valueObject.getTnhTnama()).append("%' ");
          }

          if (valueObject.getBgnBnama() != null) {
              if (first) { first = false; }
              sql.append("AND BGN_BNAMA LIKE '").append(valueObject.getBgnBnama()).append("%' ");
          }

          if (valueObject.getStbSnama() != null) {
              if (first) { first = false; }
              sql.append("AND STB_SNAMA LIKE '").append(valueObject.getStbSnama()).append("%' ");
          }

          if (valueObject.getKwsKwkod() != null) {
              if (first) { first = false; }
              sql.append("AND KWS_KWKOD LIKE '").append(valueObject.getKwsKwkod()).append("%' ");
          }

          if (valueObject.getKwsKnama() != null) {
              if (first) { first = false; }
              sql.append("AND KWS_KNAMA LIKE '").append(valueObject.getKwsKnama()).append("%' ");
          }

          if (valueObject.getKwsMkkod() != null) {
              if (first) { first = false; }
              sql.append("AND KWS_MKKOD LIKE '").append(valueObject.getKwsMkkod()).append("%' ");
          }

          if (valueObject.getMkmMkkod() != null) {
              if (first) { first = false; }
              sql.append("AND MKM_MKKOD LIKE '").append(valueObject.getMkmMkkod()).append("%' ");
          }

          if (valueObject.getMkmMnama() != null) {
              if (first) { first = false; }
              sql.append("AND MKM_MNAMA LIKE '").append(valueObject.getMkmMnama()).append("%' ");
          }

          if (valueObject.getPegHtang() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_HTANG LIKE '").append(valueObject.getPegHtang()).append("%' ");
          }

          if (valueObject.getPytStats() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_STATS LIKE '").append(valueObject.getPytStats()).append("%' ");
          }

          if (valueObject.getPytTgkct() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_TGKCT LIKE '").append(valueObject.getPytTgkct()).append("%' ");
          }

          if (valueObject.getPytTgkdd() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_TGKDD LIKE '").append(valueObject.getPytTgkdd()).append("%' ");
          }

          if (valueObject.getPytTgkne() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_TGKNE LIKE '").append(valueObject.getPytTgkne()).append("%' ");
          }

          if (valueObject.getPytTgkwf() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_TGKWF LIKE '").append(valueObject.getPytTgkwf()).append("%' ");
          }

          if (valueObject.getPytTgknd() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_TGKND LIKE '").append(valueObject.getPytTgknd()).append("%' ");
          }

          if (valueObject.getPytCtsir() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_CTSIR LIKE '").append(valueObject.getPytCtsir()).append("%' ");
          }

          if (valueObject.getPytDenda() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_DENDA LIKE '").append(valueObject.getPytDenda()).append("%' ");
          }

          if (valueObject.getPytNotis() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_NOTIS LIKE '").append(valueObject.getPytNotis()).append("%' ");
          }

          if (valueObject.getPytWaran() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_WARAN LIKE '").append(valueObject.getPytWaran()).append("%' ");
          }

          if (valueObject.getPytAmnod() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_AMNOD LIKE '").append(valueObject.getPytAmnod()).append("%' ");
          }

          if (valueObject.getPytBytct() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYTCT LIKE '").append(valueObject.getPytBytct()).append("%' ");
          }

          if (valueObject.getPytBytdd() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYTDD LIKE '").append(valueObject.getPytBytdd()).append("%' ");
          }

          if (valueObject.getPytBytne() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYTNE LIKE '").append(valueObject.getPytBytne()).append("%' ");
          }

          if (valueObject.getPytBytwf() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYTWF LIKE '").append(valueObject.getPytBytwf()).append("%' ");
          }

          if (valueObject.getPytBytod() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYTOD LIKE '").append(valueObject.getPytBytod()).append("%' ");
          }

          if (valueObject.getPytBysct() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYSCT LIKE '").append(valueObject.getPytBysct()).append("%' ");
          }

          if (valueObject.getPytBysdd() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYSDD LIKE '").append(valueObject.getPytBysdd()).append("%' ");
          }

          if (valueObject.getPytBysne() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYSNE LIKE '").append(valueObject.getPytBysne()).append("%' ");
          }

          if (valueObject.getPytByswf() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYSWF LIKE '").append(valueObject.getPytByswf()).append("%' ");
          }

          if (valueObject.getPytBysod() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_BYSOD LIKE '").append(valueObject.getPytBysod()).append("%' ");
          }

          if (valueObject.getPytTmpoh() != null) {
              if (first) { first = false; }
              sql.append("AND PYT_TMPOH LIKE '").append(valueObject.getPytTmpoh()).append("%' ");
          }


          sql.append("ORDER BY PEG_AKAUN ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, HVctcr valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setPegAkaun(result.getString("PEG_AKAUN")); 
                   valueObject.setPegDigit(result.getString("PEG_DIGIT")); 
                   valueObject.setPegJlkod(result.getString("PEG_JLKOD")); 
                   valueObject.setPegThkod(result.getString("PEG_THKOD")); 
                   valueObject.setPegHtkod(result.getString("PEG_HTKOD")); 
                   valueObject.setPegJpkod(result.getString("PEG_JPKOD")); 
                   valueObject.setPegBgkod(result.getString("PEG_BGKOD")); 
                   valueObject.setPegStkod(result.getString("PEG_STKOD")); 
                   valueObject.setPegNolot(result.getString("PEG_NOLOT")); 
                   valueObject.setPegBllot(result.getString("PEG_BLLOT")); 
                   valueObject.setPegNompt(result.getString("PEG_NOMPT")); 
                   valueObject.setPegPelan(result.getString("PEG_PELAN")); 
                   valueObject.setPegAdpg1(result.getString("PEG_ADPG1")); 
                   valueObject.setPegTkhoc(result.getString("PEG_TKHOC")); 
                   valueObject.setPegTkhtk(result.getString("PEG_TKHTK")); 
                   valueObject.setPegTkhpl(result.getString("PEG_TKHPL")); 
                   valueObject.setPegNilth(result.getString("PEG_NILTH")); 
                   valueObject.setPegBilpk(result.getString("PEG_BILPK")); 
                   valueObject.setPegLsbgn(result.getString("PEG_LSBGN")); 
                   valueObject.setPegLstnh(result.getString("PEG_LSTNH")); 
                   valueObject.setPegRjfil(result.getString("PEG_RJFIL")); 
                   valueObject.setPegRjmmk(result.getString("PEG_RJMMK")); 
                   valueObject.setPegStatf(result.getString("PEG_STATF")); 
                   valueObject.setPegOldac(result.getString("PEG_OLDAC")); 
                   valueObject.setPegStatk(result.getString("PEG_STATK")); 
                   valueObject.setPegStcbk(result.getString("PEG_STCBK")); 
                   valueObject.setPegOnama(result.getString("PEG_ONAMA")); 
                   valueObject.setPegLsans(result.getString("PEG_LSANS")); 
                   valueObject.setPegAdpg2(result.getString("PEG_ADPG2")); 
                   valueObject.setPegAklsn(result.getString("PEG_AKLSN")); 
                   valueObject.setPegAkswn(result.getString("PEG_AKSWN")); 
                   valueObject.setPegAkpbg(result.getString("PEG_AKPBG")); 
                   valueObject.setPegSmpah(result.getString("PEG_SMPAH")); 
                   valueObject.setPegCodex(result.getString("PEG_CODEX")); 
                   valueObject.setPegCodey(result.getString("PEG_CODEY")); 
                   valueObject.setPegDiskn(result.getString("PEG_DISKN")); 
                   valueObject.setPmkAkaun(result.getString("PMK_AKAUN")); 
                   valueObject.setPmkPlgid(result.getString("PMK_PLGID")); 
                   valueObject.setPmkNmbil(result.getString("PMK_NMBIL")); 
                   valueObject.setPmkBlpmk(result.getString("PMK_BLPMK")); 
                   valueObject.setPmkHkmlk(result.getString("PMK_HKMLK")); 
                   valueObject.setPmkKdans(result.getString("PMK_KDANS")); 
                   valueObject.setPmkKdexp(result.getString("PMK_KDEXP")); 
                   valueObject.setPmkPrtus(result.getString("PMK_PRTUS")); 
                   valueObject.setPmkRujmj(result.getString("PMK_RUJMJ")); 
                   valueObject.setPmkJilid(result.getString("PMK_JILID")); 
                   valueObject.setPmkStatf(result.getString("PMK_STATF")); 
                   valueObject.setPmkStang(result.getString("PMK_STANG")); 
                   valueObject.setPmkKppek(result.getString("PMK_KPPEK")); 
                   valueObject.setPmkAmtid(result.getString("PMK_AMTID")); 
                   valueObject.setPmkOnama(result.getString("PMK_ONAMA")); 
                   valueObject.setJlnKwkod(result.getString("JLN_KWKOD")); 
                   valueObject.setJlnKnama(result.getString("JLN_KNAMA")); 
                   valueObject.setJlnJlkod(result.getString("JLN_JLKOD")); 
                   valueObject.setJlnJnama(result.getString("JLN_JNAMA")); 
                   valueObject.setJlnPoskd(result.getString("JLN_POSKD")); 
                   valueObject.setJlnNegri(result.getString("JLN_NEGRI")); 
                   valueObject.setJlnPskod(result.getString("JLN_PSKOD")); 
                   valueObject.setKawKwkod(result.getString("KAW_KWKOD")); 
                   valueObject.setKawHtkod(result.getString("KAW_HTKOD")); 
                   valueObject.setKawKadar(result.getString("KAW_KADAR")); 
                   valueObject.setJpkJpkod(result.getString("JPK_JPKOD")); 
                   valueObject.setJpkItkod(result.getString("JPK_ITKOD")); 
                   valueObject.setJpkJnama(result.getString("JPK_JNAMA")); 
                   valueObject.setJpkStcbk(result.getString("JPK_STCBK")); 
                   valueObject.setPegWstatf(result.getString("PEG_WSTATF")); 
                   valueObject.setPmkWstatf(result.getString("PMK_WSTATF")); 
                   valueObject.setPmkWkdans(result.getString("PMK_WKDANS")); 
                   valueObject.setPmkWkdexp(result.getString("PMK_WKDEXP")); 
                   valueObject.setPegTksir(result.getString("PEG_TKSIR")); 
                   valueObject.setTknTksr1(result.getString("TKN_TKSR1")); 
                   valueObject.setTknTksr2(result.getString("TKN_TKSR2")); 
                   valueObject.setTknAdpg1(result.getString("TKN_ADPG1")); 
                   valueObject.setTknAdpg2(result.getString("TKN_ADPG2")); 
                   valueObject.setTknAdpg3(result.getString("TKN_ADPG3")); 
                   valueObject.setTknAdpg4(result.getString("TKN_ADPG4")); 
                   valueObject.setTknNoakn(result.getString("TKN_NOAKN")); 
                   valueObject.setTknBcode(result.getString("TKN_BCODE")); 
                   valueObject.setPvdPlgid(result.getString("PVD_PLGID")); 
                   valueObject.setPvdJenpg(result.getString("PVD_JENPG")); 
                   valueObject.setPvdAmtid(result.getString("PVD_AMTID")); 
                   valueObject.setPvdModin(result.getString("PVD_MODIN")); 
                   valueObject.setPvdAkaun(result.getString("PVD_AKAUN")); 
                   valueObject.setPvdPnama(result.getString("PVD_PNAMA")); 
                   valueObject.setPvdAlmt1(result.getString("PVD_ALMT1")); 
                   valueObject.setPvdAlmt2(result.getString("PVD_ALMT2")); 
                   valueObject.setPvdAlmt3(result.getString("PVD_ALMT3")); 
                   valueObject.setPvdAlmt4(result.getString("PVD_ALMT4")); 
                   valueObject.setPvdAlmt5(result.getString("PVD_ALMT5")); 
                   valueObject.setPvdOvsea(result.getString("PVD_OVSEA")); 
                   valueObject.setPvdEmail(result.getString("PVD_EMAIL")); 
                   valueObject.setPvdNotel(result.getString("PVD_NOTEL")); 
                   valueObject.setPvdNomhp(result.getString("PVD_NOMHP")); 
                   valueObject.setPvdNofax(result.getString("PVD_NOFAX")); 
                   valueObject.setPvdWbngsa(result.getString("PVD_WBNGSA")); 
                   valueObject.setPvdWkbgsa(result.getString("PVD_WKBGSA")); 
                   valueObject.setPvdAlmt0(result.getString("PVD_ALMT0")); 
                   valueObject.setHrtHnama(result.getString("HRT_HNAMA")); 
                   valueObject.setTnhTnama(result.getString("TNH_TNAMA")); 
                   valueObject.setBgnBnama(result.getString("BGN_BNAMA")); 
                   valueObject.setStbSnama(result.getString("STB_SNAMA")); 
                   valueObject.setKwsKwkod(result.getString("KWS_KWKOD")); 
                   valueObject.setKwsKnama(result.getString("KWS_KNAMA")); 
                   valueObject.setKwsMkkod(result.getString("KWS_MKKOD")); 
                   valueObject.setMkmMkkod(result.getString("MKM_MKKOD")); 
                   valueObject.setMkmMnama(result.getString("MKM_MNAMA")); 
                   valueObject.setPegHtang(result.getString("PEG_HTANG")); 
                   valueObject.setPytStats(result.getString("PYT_STATS")); 
                   valueObject.setPytTgkct(result.getString("PYT_TGKCT")); 
                   valueObject.setPytTgkdd(result.getString("PYT_TGKDD")); 
                   valueObject.setPytTgkne(result.getString("PYT_TGKNE")); 
                   valueObject.setPytTgkwf(result.getString("PYT_TGKWF")); 
                   valueObject.setPytTgknd(result.getString("PYT_TGKND")); 
                   valueObject.setPytCtsir(result.getString("PYT_CTSIR")); 
                   valueObject.setPytDenda(result.getString("PYT_DENDA")); 
                   valueObject.setPytNotis(result.getString("PYT_NOTIS")); 
                   valueObject.setPytWaran(result.getString("PYT_WARAN")); 
                   valueObject.setPytAmnod(result.getString("PYT_AMNOD")); 
                   valueObject.setPytBytct(result.getString("PYT_BYTCT")); 
                   valueObject.setPytBytdd(result.getString("PYT_BYTDD")); 
                   valueObject.setPytBytne(result.getString("PYT_BYTNE")); 
                   valueObject.setPytBytwf(result.getString("PYT_BYTWF")); 
                   valueObject.setPytBytod(result.getString("PYT_BYTOD")); 
                   valueObject.setPytBysct(result.getString("PYT_BYSCT")); 
                   valueObject.setPytBysdd(result.getString("PYT_BYSDD")); 
                   valueObject.setPytBysne(result.getString("PYT_BYSNE")); 
                   valueObject.setPytByswf(result.getString("PYT_BYSWF")); 
                   valueObject.setPytBysod(result.getString("PYT_BYSOD")); 
                   valueObject.setPytTmpoh(result.getString("PYT_TMPOH")); 

              } else {
                    //System.out.println("HVctcr Object Not Found!");
                    throw new NotFoundException("HVctcr Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   HVctcr temp = createValueObject();

                   temp.setPegAkaun(result.getString("PEG_AKAUN")); 
                   temp.setPegDigit(result.getString("PEG_DIGIT")); 
                   temp.setPegJlkod(result.getString("PEG_JLKOD")); 
                   temp.setPegThkod(result.getString("PEG_THKOD")); 
                   temp.setPegHtkod(result.getString("PEG_HTKOD")); 
                   temp.setPegJpkod(result.getString("PEG_JPKOD")); 
                   temp.setPegBgkod(result.getString("PEG_BGKOD")); 
                   temp.setPegStkod(result.getString("PEG_STKOD")); 
                   temp.setPegNolot(result.getString("PEG_NOLOT")); 
                   temp.setPegBllot(result.getString("PEG_BLLOT")); 
                   temp.setPegNompt(result.getString("PEG_NOMPT")); 
                   temp.setPegPelan(result.getString("PEG_PELAN")); 
                   temp.setPegAdpg1(result.getString("PEG_ADPG1")); 
                   temp.setPegTkhoc(result.getString("PEG_TKHOC")); 
                   temp.setPegTkhtk(result.getString("PEG_TKHTK")); 
                   temp.setPegTkhpl(result.getString("PEG_TKHPL")); 
                   temp.setPegNilth(result.getString("PEG_NILTH")); 
                   temp.setPegBilpk(result.getString("PEG_BILPK")); 
                   temp.setPegLsbgn(result.getString("PEG_LSBGN")); 
                   temp.setPegLstnh(result.getString("PEG_LSTNH")); 
                   temp.setPegRjfil(result.getString("PEG_RJFIL")); 
                   temp.setPegRjmmk(result.getString("PEG_RJMMK")); 
                   temp.setPegStatf(result.getString("PEG_STATF")); 
                   temp.setPegOldac(result.getString("PEG_OLDAC")); 
                   temp.setPegStatk(result.getString("PEG_STATK")); 
                   temp.setPegStcbk(result.getString("PEG_STCBK")); 
                   temp.setPegOnama(result.getString("PEG_ONAMA")); 
                   temp.setPegLsans(result.getString("PEG_LSANS")); 
                   temp.setPegAdpg2(result.getString("PEG_ADPG2")); 
                   temp.setPegAklsn(result.getString("PEG_AKLSN")); 
                   temp.setPegAkswn(result.getString("PEG_AKSWN")); 
                   temp.setPegAkpbg(result.getString("PEG_AKPBG")); 
                   temp.setPegSmpah(result.getString("PEG_SMPAH")); 
                   temp.setPegCodex(result.getString("PEG_CODEX")); 
                   temp.setPegCodey(result.getString("PEG_CODEY")); 
                   temp.setPegDiskn(result.getString("PEG_DISKN")); 
                   temp.setPmkAkaun(result.getString("PMK_AKAUN")); 
                   temp.setPmkPlgid(result.getString("PMK_PLGID")); 
                   temp.setPmkNmbil(result.getString("PMK_NMBIL")); 
                   temp.setPmkBlpmk(result.getString("PMK_BLPMK")); 
                   temp.setPmkHkmlk(result.getString("PMK_HKMLK")); 
                   temp.setPmkKdans(result.getString("PMK_KDANS")); 
                   temp.setPmkKdexp(result.getString("PMK_KDEXP")); 
                   temp.setPmkPrtus(result.getString("PMK_PRTUS")); 
                   temp.setPmkRujmj(result.getString("PMK_RUJMJ")); 
                   temp.setPmkJilid(result.getString("PMK_JILID")); 
                   temp.setPmkStatf(result.getString("PMK_STATF")); 
                   temp.setPmkStang(result.getString("PMK_STANG")); 
                   temp.setPmkKppek(result.getString("PMK_KPPEK")); 
                   temp.setPmkAmtid(result.getString("PMK_AMTID")); 
                   temp.setPmkOnama(result.getString("PMK_ONAMA")); 
                   temp.setJlnKwkod(result.getString("JLN_KWKOD")); 
                   temp.setJlnKnama(result.getString("JLN_KNAMA")); 
                   temp.setJlnJlkod(result.getString("JLN_JLKOD")); 
                   temp.setJlnJnama(result.getString("JLN_JNAMA")); 
                   temp.setJlnPoskd(result.getString("JLN_POSKD")); 
                   temp.setJlnNegri(result.getString("JLN_NEGRI")); 
                   temp.setJlnPskod(result.getString("JLN_PSKOD")); 
                   temp.setKawKwkod(result.getString("KAW_KWKOD")); 
                   temp.setKawHtkod(result.getString("KAW_HTKOD")); 
                   temp.setKawKadar(result.getString("KAW_KADAR")); 
                   temp.setJpkJpkod(result.getString("JPK_JPKOD")); 
                   temp.setJpkItkod(result.getString("JPK_ITKOD")); 
                   temp.setJpkJnama(result.getString("JPK_JNAMA")); 
                   temp.setJpkStcbk(result.getString("JPK_STCBK")); 
                   temp.setPegWstatf(result.getString("PEG_WSTATF")); 
                   temp.setPmkWstatf(result.getString("PMK_WSTATF")); 
                   temp.setPmkWkdans(result.getString("PMK_WKDANS")); 
                   temp.setPmkWkdexp(result.getString("PMK_WKDEXP")); 
                   temp.setPegTksir(result.getString("PEG_TKSIR")); 
                   temp.setTknTksr1(result.getString("TKN_TKSR1")); 
                   temp.setTknTksr2(result.getString("TKN_TKSR2")); 
                   temp.setTknAdpg1(result.getString("TKN_ADPG1")); 
                   temp.setTknAdpg2(result.getString("TKN_ADPG2")); 
                   temp.setTknAdpg3(result.getString("TKN_ADPG3")); 
                   temp.setTknAdpg4(result.getString("TKN_ADPG4")); 
                   temp.setTknNoakn(result.getString("TKN_NOAKN")); 
                   temp.setTknBcode(result.getString("TKN_BCODE")); 
                   temp.setPvdPlgid(result.getString("PVD_PLGID")); 
                   temp.setPvdJenpg(result.getString("PVD_JENPG")); 
                   temp.setPvdAmtid(result.getString("PVD_AMTID")); 
                   temp.setPvdModin(result.getString("PVD_MODIN")); 
                   temp.setPvdAkaun(result.getString("PVD_AKAUN")); 
                   temp.setPvdPnama(result.getString("PVD_PNAMA")); 
                   temp.setPvdAlmt1(result.getString("PVD_ALMT1")); 
                   temp.setPvdAlmt2(result.getString("PVD_ALMT2")); 
                   temp.setPvdAlmt3(result.getString("PVD_ALMT3")); 
                   temp.setPvdAlmt4(result.getString("PVD_ALMT4")); 
                   temp.setPvdAlmt5(result.getString("PVD_ALMT5")); 
                   temp.setPvdOvsea(result.getString("PVD_OVSEA")); 
                   temp.setPvdEmail(result.getString("PVD_EMAIL")); 
                   temp.setPvdNotel(result.getString("PVD_NOTEL")); 
                   temp.setPvdNomhp(result.getString("PVD_NOMHP")); 
                   temp.setPvdNofax(result.getString("PVD_NOFAX")); 
                   temp.setPvdWbngsa(result.getString("PVD_WBNGSA")); 
                   temp.setPvdWkbgsa(result.getString("PVD_WKBGSA")); 
                   temp.setPvdAlmt0(result.getString("PVD_ALMT0")); 
                   temp.setHrtHnama(result.getString("HRT_HNAMA")); 
                   temp.setTnhTnama(result.getString("TNH_TNAMA")); 
                   temp.setBgnBnama(result.getString("BGN_BNAMA")); 
                   temp.setStbSnama(result.getString("STB_SNAMA")); 
                   temp.setKwsKwkod(result.getString("KWS_KWKOD")); 
                   temp.setKwsKnama(result.getString("KWS_KNAMA")); 
                   temp.setKwsMkkod(result.getString("KWS_MKKOD")); 
                   temp.setMkmMkkod(result.getString("MKM_MKKOD")); 
                   temp.setMkmMnama(result.getString("MKM_MNAMA")); 
                   temp.setPegHtang(result.getString("PEG_HTANG")); 
                   temp.setPytStats(result.getString("PYT_STATS")); 
                   temp.setPytTgkct(result.getString("PYT_TGKCT")); 
                   temp.setPytTgkdd(result.getString("PYT_TGKDD")); 
                   temp.setPytTgkne(result.getString("PYT_TGKNE")); 
                   temp.setPytTgkwf(result.getString("PYT_TGKWF")); 
                   temp.setPytTgknd(result.getString("PYT_TGKND")); 
                   temp.setPytCtsir(result.getString("PYT_CTSIR")); 
                   temp.setPytDenda(result.getString("PYT_DENDA")); 
                   temp.setPytNotis(result.getString("PYT_NOTIS")); 
                   temp.setPytWaran(result.getString("PYT_WARAN")); 
                   temp.setPytAmnod(result.getString("PYT_AMNOD")); 
                   temp.setPytBytct(result.getString("PYT_BYTCT")); 
                   temp.setPytBytdd(result.getString("PYT_BYTDD")); 
                   temp.setPytBytne(result.getString("PYT_BYTNE")); 
                   temp.setPytBytwf(result.getString("PYT_BYTWF")); 
                   temp.setPytBytod(result.getString("PYT_BYTOD")); 
                   temp.setPytBysct(result.getString("PYT_BYSCT")); 
                   temp.setPytBysdd(result.getString("PYT_BYSDD")); 
                   temp.setPytBysne(result.getString("PYT_BYSNE")); 
                   temp.setPytByswf(result.getString("PYT_BYSWF")); 
                   temp.setPytBysod(result.getString("PYT_BYSOD")); 
                   temp.setPytTmpoh(result.getString("PYT_TMPOH")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}
