package com.epbt2.mtkn.tanya.dao;

import com.epbt2.util.NotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;





 /**
  * HVhtgk Data Access Object (DAO).
  * This class contains all database handling that is needed to 
  * permanently store and retrieve HVhtgk object instances. 
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HVhtgkDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public HVhtgk createValueObject() {
          return new HVhtgk();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public HVhtgk getObject(Connection conn, String PEgakaun) throws NotFoundException, SQLException {

          HVhtgk valueObject = createValueObject();
          valueObject.setPEgakaun(PEgakaun);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, HVhtgk valueObject) throws NotFoundException, SQLException {

          if (valueObject.getPEgakaun() == null) {
               //System.out.println("Can not select without Primary-Key!");
               throw new NotFoundException("Can not select without Primary-Key!");
          }

          String sql = "SELECT * FROM MTKN.HVHTGK WHERE (PEG_AKAUN = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setString(1, valueObject.getPEgakaun()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM MTKN.HVHTGK WHERE ROWNUM <= 200 ORDER BY PEG_AKAUN ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, HVhtgk valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO MTKN.HVHTGK ( PEG_AKAUN, PEG_STATF, PMK_NMBIL, "
               + "ADPG1, ADPG2, ADPG3, "
               + "ADPG4, PEG_NILTH, KAW_KADAR, "
               + "PEG_TKSIR, JUM_TGKN, HTX_TMPOH) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setString(1, valueObject.getPEgakaun()); 
               stmt.setString(2, valueObject.getPEgstatf()); 
               stmt.setString(3, valueObject.getPMknmbil()); 
               stmt.setString(4, valueObject.getADpg1()); 
               stmt.setString(5, valueObject.getADpg2()); 
               stmt.setString(6, valueObject.getADpg3()); 
               stmt.setString(7, valueObject.getADpg4()); 
               stmt.setString(8, valueObject.getPEgnilth()); 
               stmt.setString(9, valueObject.getKAwkadar()); 
               stmt.setString(10, valueObject.getPEgtksir()); 
               stmt.setString(11, valueObject.getJUmtgkn()); 
               stmt.setString(12, valueObject.getHTxtmpoh()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, HVhtgk valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE MTKN.HVHTGK SET PEG_STATF = ?, PMK_NMBIL = ?, ADPG1 = ?, "
               + "ADPG2 = ?, ADPG3 = ?, ADPG4 = ?, "
               + "PEG_NILTH = ?, KAW_KADAR = ?, PEG_TKSIR = ?, "
               + "JUM_TGKN = ?, HTX_TMPOH = ? WHERE (PEG_AKAUN = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getPEgstatf()); 
              stmt.setString(2, valueObject.getPMknmbil()); 
              stmt.setString(3, valueObject.getADpg1()); 
              stmt.setString(4, valueObject.getADpg2()); 
              stmt.setString(5, valueObject.getADpg3()); 
              stmt.setString(6, valueObject.getADpg4()); 
              stmt.setString(7, valueObject.getPEgnilth()); 
              stmt.setString(8, valueObject.getKAwkadar()); 
              stmt.setString(9, valueObject.getPEgtksir()); 
              stmt.setString(10, valueObject.getJUmtgkn()); 
              stmt.setString(11, valueObject.getHTxtmpoh()); 

              stmt.setString(12, valueObject.getPEgakaun()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, HVhtgk valueObject) 
          throws NotFoundException, SQLException {

          if (valueObject.getPEgakaun() == null) {
               //System.out.println("Can not delete without Primary-Key!");
               throw new NotFoundException("Can not delete without Primary-Key!");
          }

          String sql = "DELETE FROM MTKN.HVHTGK WHERE (PEG_AKAUN = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getPEgakaun()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM MTKN.HVHTGK";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM MTKN.HVHTGK";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, HVhtgk valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM MTKN.HVHTGK WHERE 1=1 ");

          if (valueObject.getPEgakaun() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_AKAUN LIKE '").append(valueObject.getPEgakaun()).append("' ");
          }

          if (valueObject.getPEgstatf() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_STATF LIKE '").append(valueObject.getPEgstatf()).append("%' ");
          }

          if (valueObject.getPMknmbil() != null) {
              if (first) { first = false; }
              sql.append("AND PMK_NMBIL LIKE '").append(valueObject.getPMknmbil()).append("%' ");
          }

          if (valueObject.getADpg1() != null) {
              if (first) { first = false; }
              sql.append("AND ADPG1 LIKE '").append(valueObject.getADpg1()).append("%' ");
          }

          if (valueObject.getADpg2() != null) {
              if (first) { first = false; }
              sql.append("AND ADPG2 LIKE '").append(valueObject.getADpg2()).append("%' ");
          }

          if (valueObject.getADpg3() != null) {
              if (first) { first = false; }
              sql.append("AND ADPG3 LIKE '").append(valueObject.getADpg3()).append("%' ");
          }

          if (valueObject.getADpg4() != null) {
              if (first) { first = false; }
              sql.append("AND ADPG4 LIKE '").append(valueObject.getADpg4()).append("%' ");
          }

          if (valueObject.getPEgnilth() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_NILTH LIKE '").append(valueObject.getPEgnilth()).append("%' ");
          }

          if (valueObject.getKAwkadar() != null) {
              if (first) { first = false; }
              sql.append("AND KAW_KADAR LIKE '").append(valueObject.getKAwkadar()).append("%' ");
          }

          if (valueObject.getPEgtksir() != null) {
              if (first) { first = false; }
              sql.append("AND PEG_TKSIR LIKE '").append(valueObject.getPEgtksir()).append("%' ");
          }

          if (valueObject.getJUmtgkn() != null) {
              if (first) { first = false; }
              sql.append("AND JUM_TGKN LIKE '").append(valueObject.getJUmtgkn()).append("%' ");
          }

          if (valueObject.getHTxtmpoh() != null) {
              if (first) { first = false; }
              sql.append("AND HTX_TMPOH LIKE '").append(valueObject.getHTxtmpoh()).append("%' ");
          }


          sql.append("ORDER BY PEG_AKAUN ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, HVhtgk valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setPEgakaun(result.getString("PEG_AKAUN")); 
                   valueObject.setPEgstatf(result.getString("PEG_STATF")); 
                   valueObject.setPMknmbil(result.getString("PMK_NMBIL")); 
                   valueObject.setADpg1(result.getString("ADPG1")); 
                   valueObject.setADpg2(result.getString("ADPG2")); 
                   valueObject.setADpg3(result.getString("ADPG3")); 
                   valueObject.setADpg4(result.getString("ADPG4")); 
                   valueObject.setPEgnilth(result.getString("PEG_NILTH")); 
                   valueObject.setKAwkadar(result.getString("KAW_KADAR")); 
                   valueObject.setPEgtksir(result.getString("PEG_TKSIR")); 
                   valueObject.setJUmtgkn(result.getString("JUM_TGKN")); 
                   valueObject.setHTxtmpoh(result.getString("HTX_TMPOH")); 

              } else {
                    //System.out.println("HVhtgk Object Not Found!");
                    throw new NotFoundException("HVhtgk Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   HVhtgk temp = createValueObject();

                   temp.setPEgakaun(result.getString("PEG_AKAUN")); 
                   temp.setPEgstatf(result.getString("PEG_STATF")); 
                   temp.setPMknmbil(result.getString("PMK_NMBIL")); 
                   temp.setADpg1(result.getString("ADPG1")); 
                   temp.setADpg2(result.getString("ADPG2")); 
                   temp.setADpg3(result.getString("ADPG3")); 
                   temp.setADpg4(result.getString("ADPG4")); 
                   temp.setPEgnilth(result.getString("PEG_NILTH")); 
                   temp.setKAwkadar(result.getString("KAW_KADAR")); 
                   temp.setPEgtksir(result.getString("PEG_TKSIR")); 
                   temp.setJUmtgkn(result.getString("JUM_TGKN")); 
                   temp.setHTxtmpoh(result.getString("HTX_TMPOH")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}
