package com.epbt2.mtkn.tanya.dao;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * HVhtgk Value Object.
  * This class is value object representing database table MTKN.HVHTGK
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HVhtgk implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String PEgakaun;
    private String PEgstatf;
    private String PMknmbil;
    private String ADpg1;
    private String ADpg2;
    private String ADpg3;
    private String ADpg4;
    private String PEgnilth;
    private String KAwkadar;
    private String PEgtksir;
    private String JUmtgkn;
    private String HTxtmpoh;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public HVhtgk () {

    }

    public HVhtgk (String PEgakaunIn) {

          this.PEgakaun = PEgakaunIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getPEgakaun() {
          return this.PEgakaun;
    }
    public void setPEgakaun(String PEgakaunIn) {
          this.PEgakaun = PEgakaunIn;
    }

    public String getPEgstatf() {
          return this.PEgstatf;
    }
    public void setPEgstatf(String PEgstatfIn) {
          this.PEgstatf = PEgstatfIn;
    }

    public String getPMknmbil() {
          return this.PMknmbil;
    }
    public void setPMknmbil(String PMknmbilIn) {
          this.PMknmbil = PMknmbilIn;
    }

    public String getADpg1() {
          return this.ADpg1;
    }
    public void setADpg1(String ADpg1In) {
          this.ADpg1 = ADpg1In;
    }

    public String getADpg2() {
          return this.ADpg2;
    }
    public void setADpg2(String ADpg2In) {
          this.ADpg2 = ADpg2In;
    }

    public String getADpg3() {
          return this.ADpg3;
    }
    public void setADpg3(String ADpg3In) {
          this.ADpg3 = ADpg3In;
    }

    public String getADpg4() {
          return this.ADpg4;
    }
    public void setADpg4(String ADpg4In) {
          this.ADpg4 = ADpg4In;
    }

    public String getPEgnilth() {
          return this.PEgnilth;
    }
    public void setPEgnilth(String PEgnilthIn) {
          this.PEgnilth = PEgnilthIn;
    }

    public String getKAwkadar() {
          return this.KAwkadar;
    }
    public void setKAwkadar(String KAwkadarIn) {
          this.KAwkadar = KAwkadarIn;
    }

    public String getPEgtksir() {
          return this.PEgtksir;
    }
    public void setPEgtksir(String PEgtksirIn) {
          this.PEgtksir = PEgtksirIn;
    }

    public String getJUmtgkn() {
          return this.JUmtgkn;
    }
    public void setJUmtgkn(String JUmtgknIn) {
          this.JUmtgkn = JUmtgknIn;
    }

    public String getHTxtmpoh() {
          return this.HTxtmpoh;
    }
    public void setHTxtmpoh(String HTxtmpohIn) {
          this.HTxtmpoh = HTxtmpohIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String PEgakaunIn,
          String PEgstatfIn,
          String PMknmbilIn,
          String ADpg1In,
          String ADpg2In,
          String ADpg3In,
          String ADpg4In,
          String PEgnilthIn,
          String KAwkadarIn,
          String PEgtksirIn,
          String JUmtgknIn,
          String HTxtmpohIn) {
          this.PEgakaun = PEgakaunIn;
          this.PEgstatf = PEgstatfIn;
          this.PMknmbil = PMknmbilIn;
          this.ADpg1 = ADpg1In;
          this.ADpg2 = ADpg2In;
          this.ADpg3 = ADpg3In;
          this.ADpg4 = ADpg4In;
          this.PEgnilth = PEgnilthIn;
          this.KAwkadar = KAwkadarIn;
          this.PEgtksir = PEgtksirIn;
          this.JUmtgkn = JUmtgknIn;
          this.HTxtmpoh = HTxtmpohIn;
    }


    /** 
     * hasEqualMapping-method will compare two HVhtgk instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(HVhtgk valueObject) {

          if (this.PEgakaun == null) {
                    if (valueObject.getPEgakaun() != null)
                           return(false);
          } else if (!this.PEgakaun.equals(valueObject.getPEgakaun())) {
                    return(false);
          }
          if (this.PEgstatf == null) {
                    if (valueObject.getPEgstatf() != null)
                           return(false);
          } else if (!this.PEgstatf.equals(valueObject.getPEgstatf())) {
                    return(false);
          }
          if (this.PMknmbil == null) {
                    if (valueObject.getPMknmbil() != null)
                           return(false);
          } else if (!this.PMknmbil.equals(valueObject.getPMknmbil())) {
                    return(false);
          }
          if (this.ADpg1 == null) {
                    if (valueObject.getADpg1() != null)
                           return(false);
          } else if (!this.ADpg1.equals(valueObject.getADpg1())) {
                    return(false);
          }
          if (this.ADpg2 == null) {
                    if (valueObject.getADpg2() != null)
                           return(false);
          } else if (!this.ADpg2.equals(valueObject.getADpg2())) {
                    return(false);
          }
          if (this.ADpg3 == null) {
                    if (valueObject.getADpg3() != null)
                           return(false);
          } else if (!this.ADpg3.equals(valueObject.getADpg3())) {
                    return(false);
          }
          if (this.ADpg4 == null) {
                    if (valueObject.getADpg4() != null)
                           return(false);
          } else if (!this.ADpg4.equals(valueObject.getADpg4())) {
                    return(false);
          }
          if (this.PEgnilth == null) {
                    if (valueObject.getPEgnilth() != null)
                           return(false);
          } else if (!this.PEgnilth.equals(valueObject.getPEgnilth())) {
                    return(false);
          }
          if (this.KAwkadar == null) {
                    if (valueObject.getKAwkadar() != null)
                           return(false);
          } else if (!this.KAwkadar.equals(valueObject.getKAwkadar())) {
                    return(false);
          }
          if (this.PEgtksir == null) {
                    if (valueObject.getPEgtksir() != null)
                           return(false);
          } else if (!this.PEgtksir.equals(valueObject.getPEgtksir())) {
                    return(false);
          }
          if (this.JUmtgkn == null) {
                    if (valueObject.getJUmtgkn() != null)
                           return(false);
          } else if (!this.JUmtgkn.equals(valueObject.getJUmtgkn())) {
                    return(false);
          }
          if (this.HTxtmpoh == null) {
                    if (valueObject.getHTxtmpoh() != null)
                           return(false);
          } else if (!this.HTxtmpoh.equals(valueObject.getHTxtmpoh())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass HVhtgk, mapping to table MTKN.HVHTGK\n");
        out.append("Persistent attributes: \n"); 
        out.append("PEgakaun = " + this.PEgakaun + "\n"); 
        out.append("PEgstatf = " + this.PEgstatf + "\n"); 
        out.append("PMknmbil = " + this.PMknmbil + "\n"); 
        out.append("ADpg1 = " + this.ADpg1 + "\n"); 
        out.append("ADpg2 = " + this.ADpg2 + "\n"); 
        out.append("ADpg3 = " + this.ADpg3 + "\n"); 
        out.append("ADpg4 = " + this.ADpg4 + "\n"); 
        out.append("PEgnilth = " + this.PEgnilth + "\n"); 
        out.append("KAwkadar = " + this.KAwkadar + "\n"); 
        out.append("PEgtksir = " + this.PEgtksir + "\n"); 
        out.append("JUmtgkn = " + this.JUmtgkn + "\n"); 
        out.append("HTxtmpoh = " + this.HTxtmpoh + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        HVhtgk cloned = new HVhtgk();

        if (this.PEgakaun != null)
             cloned.setPEgakaun(new String(this.PEgakaun)); 
        if (this.PEgstatf != null)
             cloned.setPEgstatf(new String(this.PEgstatf)); 
        if (this.PMknmbil != null)
             cloned.setPMknmbil(new String(this.PMknmbil)); 
        if (this.ADpg1 != null)
             cloned.setADpg1(new String(this.ADpg1)); 
        if (this.ADpg2 != null)
             cloned.setADpg2(new String(this.ADpg2)); 
        if (this.ADpg3 != null)
             cloned.setADpg3(new String(this.ADpg3)); 
        if (this.ADpg4 != null)
             cloned.setADpg4(new String(this.ADpg4)); 
        if (this.PEgnilth != null)
             cloned.setPEgnilth(new String(this.PEgnilth)); 
        if (this.KAwkadar != null)
             cloned.setKAwkadar(new String(this.KAwkadar)); 
        if (this.PEgtksir != null)
             cloned.setPEgtksir(new String(this.PEgtksir)); 
        if (this.JUmtgkn != null)
             cloned.setJUmtgkn(new String(this.JUmtgkn)); 
        if (this.HTxtmpoh != null)
             cloned.setHTxtmpoh(new String(this.HTxtmpoh)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}