package com.epbt2.mtkn.tanya.dao;


import java.io.*;

 /**
  * HVmjc1 Value Object.
  * This class is value object representing database table HVmjc1
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HVmjc1 implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String VMjlebh1;
    private String VMjcmsms;
    private String VMjcmtgk;
    private String VMjcysms;
    private String VMjcytgk;
    private String VMjdmsms;
    private String VMjdmtgk;
    private String VMjdysms;
    private String VMjamsms;
    private String VMjamtgk;
    private String VMjaysms;
    private String VMjaytgk;
    private String VMjbmsms;
    private String VMjbmtgk;
    private String VMjbysms;
    private String VMjbytgk;
    private String VMjdytgk;

    /*BYE - 29/04/2014*/
    
    private String VMjfmsms;
    private String VMjfmtgk;
    private String VMjfysms;
    private String VMjfytgk;

    public String getVMjfmsms() {
        return VMjfmsms;
    }

    public void setVMjfmsms(String VMjfmsms) {
        this.VMjfmsms = VMjfmsms;
    }

    public String getVMjfmtgk() {
        return VMjfmtgk;
    }

    public void setVMjfmtgk(String VMjfmtgk) {
        this.VMjfmtgk = VMjfmtgk;
    }

    public String getVMjfysms() {
        return VMjfysms;
    }

    public void setVMjfysms(String VMjfysms) {
        this.VMjfysms = VMjfysms;
    }

    public String getVMjfytgk() {
        return VMjfytgk;
    }

    public void setVMjfytgk(String VMjfytgk) {
        this.VMjfytgk = VMjfytgk;
    }
    /*BYE - 29/04/2014*/


    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public HVmjc1 () {

    }

    public HVmjc1 (String VMjlebh1In) {

          this.VMjlebh1 = VMjlebh1In;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getVMjlebh1() {
          return this.VMjlebh1;
    }
    public void setVMjlebh1(String VMjlebh1In) {
          this.VMjlebh1 = VMjlebh1In;
    }

    public String getVMjcmsms() {
          return this.VMjcmsms;
    }
    public void setVMjcmsms(String VMjcmsmsIn) {
          this.VMjcmsms = VMjcmsmsIn;
    }

    public String getVMjcmtgk() {
          return this.VMjcmtgk;
    }
    public void setVMjcmtgk(String VMjcmtgkIn) {
          this.VMjcmtgk = VMjcmtgkIn;
    }

    public String getVMjcysms() {
          return this.VMjcysms;
    }
    public void setVMjcysms(String VMjcysmsIn) {
          this.VMjcysms = VMjcysmsIn;
    }

    public String getVMjcytgk() {
          return this.VMjcytgk;
    }
    public void setVMjcytgk(String VMjcytgkIn) {
          this.VMjcytgk = VMjcytgkIn;
    }

    public String getVMjdmsms() {
          return this.VMjdmsms;
    }
    public void setVMjdmsms(String VMjdmsmsIn) {
          this.VMjdmsms = VMjdmsmsIn;
    }

    public String getVMjdmtgk() {
          return this.VMjdmtgk;
    }
    public void setVMjdmtgk(String VMjdmtgkIn) {
          this.VMjdmtgk = VMjdmtgkIn;
    }

    public String getVMjdysms() {
          return this.VMjdysms;
    }
    public void setVMjdysms(String VMjdysmsIn) {
          this.VMjdysms = VMjdysmsIn;
    }

    public String getVMjamsms() {
          return this.VMjamsms;
    }
    public void setVMjamsms(String VMjamsmsIn) {
          this.VMjamsms = VMjamsmsIn;
    }

    public String getVMjamtgk() {
          return this.VMjamtgk;
    }
    public void setVMjamtgk(String VMjamtgkIn) {
          this.VMjamtgk = VMjamtgkIn;
    }

    public String getVMjaysms() {
          return this.VMjaysms;
    }
    public void setVMjaysms(String VMjaysmsIn) {
          this.VMjaysms = VMjaysmsIn;
    }

    public String getVMjaytgk() {
          return this.VMjaytgk;
    }
    public void setVMjaytgk(String VMjaytgkIn) {
          this.VMjaytgk = VMjaytgkIn;
    }

    public String getVMjbmsms() {
          return this.VMjbmsms;
    }
    public void setVMjbmsms(String VMjbmsmsIn) {
          this.VMjbmsms = VMjbmsmsIn;
    }

    public String getVMjbmtgk() {
          return this.VMjbmtgk;
    }
    public void setVMjbmtgk(String VMjbmtgkIn) {
          this.VMjbmtgk = VMjbmtgkIn;
    }

    public String getVMjbysms() {
          return this.VMjbysms;
    }
    public void setVMjbysms(String VMjbysmsIn) {
          this.VMjbysms = VMjbysmsIn;
    }

    public String getVMjbytgk() {
          return this.VMjbytgk;
    }
    public void setVMjbytgk(String VMjbytgkIn) {
          this.VMjbytgk = VMjbytgkIn;
    }

    public String getVMjdytgk() {
          return this.VMjdytgk;
    }
    public void setVMjdytgk(String VMjdytgkIn) {
          this.VMjdytgk = VMjdytgkIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String VMjlebh1In,
          String VMjcmsmsIn,
          String VMjcmtgkIn,
          String VMjcysmsIn,
          String VMjcytgkIn,
          String VMjdmsmsIn,
          String VMjdmtgkIn,
          String VMjdysmsIn,
          String VMjamsmsIn,
          String VMjamtgkIn,
          String VMjaysmsIn,
          String VMjaytgkIn,
          String VMjbmsmsIn,
          String VMjbmtgkIn,
          String VMjbysmsIn,
          String VMjbytgkIn,
          String VMjdytgkIn) {
          this.VMjlebh1 = VMjlebh1In;
          this.VMjcmsms = VMjcmsmsIn;
          this.VMjcmtgk = VMjcmtgkIn;
          this.VMjcysms = VMjcysmsIn;
          this.VMjcytgk = VMjcytgkIn;
          this.VMjdmsms = VMjdmsmsIn;
          this.VMjdmtgk = VMjdmtgkIn;
          this.VMjdysms = VMjdysmsIn;
          this.VMjamsms = VMjamsmsIn;
          this.VMjamtgk = VMjamtgkIn;
          this.VMjaysms = VMjaysmsIn;
          this.VMjaytgk = VMjaytgkIn;
          this.VMjbmsms = VMjbmsmsIn;
          this.VMjbmtgk = VMjbmtgkIn;
          this.VMjbysms = VMjbysmsIn;
          this.VMjbytgk = VMjbytgkIn;
          this.VMjdytgk = VMjdytgkIn;
    }


    /** 
     * hasEqualMapping-method will compare two HVmjc1 instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(HVmjc1 valueObject) {

          if (this.VMjlebh1 == null) {
                    if (valueObject.getVMjlebh1() != null)
                           return(false);
          } else if (!this.VMjlebh1.equals(valueObject.getVMjlebh1())) {
                    return(false);
          }
          if (this.VMjcmsms == null) {
                    if (valueObject.getVMjcmsms() != null)
                           return(false);
          } else if (!this.VMjcmsms.equals(valueObject.getVMjcmsms())) {
                    return(false);
          }
          if (this.VMjcmtgk == null) {
                    if (valueObject.getVMjcmtgk() != null)
                           return(false);
          } else if (!this.VMjcmtgk.equals(valueObject.getVMjcmtgk())) {
                    return(false);
          }
          if (this.VMjcysms == null) {
                    if (valueObject.getVMjcysms() != null)
                           return(false);
          } else if (!this.VMjcysms.equals(valueObject.getVMjcysms())) {
                    return(false);
          }
          if (this.VMjcytgk == null) {
                    if (valueObject.getVMjcytgk() != null)
                           return(false);
          } else if (!this.VMjcytgk.equals(valueObject.getVMjcytgk())) {
                    return(false);
          }
          if (this.VMjdmsms == null) {
                    if (valueObject.getVMjdmsms() != null)
                           return(false);
          } else if (!this.VMjdmsms.equals(valueObject.getVMjdmsms())) {
                    return(false);
          }
          if (this.VMjdmtgk == null) {
                    if (valueObject.getVMjdmtgk() != null)
                           return(false);
          } else if (!this.VMjdmtgk.equals(valueObject.getVMjdmtgk())) {
                    return(false);
          }
          if (this.VMjdysms == null) {
                    if (valueObject.getVMjdysms() != null)
                           return(false);
          } else if (!this.VMjdysms.equals(valueObject.getVMjdysms())) {
                    return(false);
          }
          if (this.VMjamsms == null) {
                    if (valueObject.getVMjamsms() != null)
                           return(false);
          } else if (!this.VMjamsms.equals(valueObject.getVMjamsms())) {
                    return(false);
          }
          if (this.VMjamtgk == null) {
                    if (valueObject.getVMjamtgk() != null)
                           return(false);
          } else if (!this.VMjamtgk.equals(valueObject.getVMjamtgk())) {
                    return(false);
          }
          if (this.VMjaysms == null) {
                    if (valueObject.getVMjaysms() != null)
                           return(false);
          } else if (!this.VMjaysms.equals(valueObject.getVMjaysms())) {
                    return(false);
          }
          if (this.VMjaytgk == null) {
                    if (valueObject.getVMjaytgk() != null)
                           return(false);
          } else if (!this.VMjaytgk.equals(valueObject.getVMjaytgk())) {
                    return(false);
          }
          if (this.VMjbmsms == null) {
                    if (valueObject.getVMjbmsms() != null)
                           return(false);
          } else if (!this.VMjbmsms.equals(valueObject.getVMjbmsms())) {
                    return(false);
          }
          if (this.VMjbmtgk == null) {
                    if (valueObject.getVMjbmtgk() != null)
                           return(false);
          } else if (!this.VMjbmtgk.equals(valueObject.getVMjbmtgk())) {
                    return(false);
          }
          if (this.VMjbysms == null) {
                    if (valueObject.getVMjbysms() != null)
                           return(false);
          } else if (!this.VMjbysms.equals(valueObject.getVMjbysms())) {
                    return(false);
          }
          if (this.VMjbytgk == null) {
                    if (valueObject.getVMjbytgk() != null)
                           return(false);
          } else if (!this.VMjbytgk.equals(valueObject.getVMjbytgk())) {
                    return(false);
          }
          if (this.VMjdytgk == null) {
                    if (valueObject.getVMjdytgk() != null)
                           return(false);
          } else if (!this.VMjdytgk.equals(valueObject.getVMjdytgk())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass HVmjc1, mapping to table HVmjc1\n");
        out.append("Persistent attributes: \n"); 
        out.append("VMjlebh1 = " + this.VMjlebh1 + "\n"); 
        out.append("VMjcmsms = " + this.VMjcmsms + "\n"); 
        out.append("VMjcmtgk = " + this.VMjcmtgk + "\n"); 
        out.append("VMjcysms = " + this.VMjcysms + "\n"); 
        out.append("VMjcytgk = " + this.VMjcytgk + "\n"); 
        out.append("VMjdmsms = " + this.VMjdmsms + "\n"); 
        out.append("VMjdmtgk = " + this.VMjdmtgk + "\n"); 
        out.append("VMjdysms = " + this.VMjdysms + "\n"); 
        out.append("VMjamsms = " + this.VMjamsms + "\n"); 
        out.append("VMjamtgk = " + this.VMjamtgk + "\n"); 
        out.append("VMjaysms = " + this.VMjaysms + "\n"); 
        out.append("VMjaytgk = " + this.VMjaytgk + "\n"); 
        out.append("VMjbmsms = " + this.VMjbmsms + "\n"); 
        out.append("VMjbmtgk = " + this.VMjbmtgk + "\n"); 
        out.append("VMjbysms = " + this.VMjbysms + "\n"); 
        out.append("VMjbytgk = " + this.VMjbytgk + "\n"); 
        out.append("VMjdytgk = " + this.VMjdytgk + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        HVmjc1 cloned = new HVmjc1();

        if (this.VMjlebh1 != null)
             cloned.setVMjlebh1(new String(this.VMjlebh1)); 
        if (this.VMjcmsms != null)
             cloned.setVMjcmsms(new String(this.VMjcmsms)); 
        if (this.VMjcmtgk != null)
             cloned.setVMjcmtgk(new String(this.VMjcmtgk)); 
        if (this.VMjcysms != null)
             cloned.setVMjcysms(new String(this.VMjcysms)); 
        if (this.VMjcytgk != null)
             cloned.setVMjcytgk(new String(this.VMjcytgk)); 
        if (this.VMjdmsms != null)
             cloned.setVMjdmsms(new String(this.VMjdmsms)); 
        if (this.VMjdmtgk != null)
             cloned.setVMjdmtgk(new String(this.VMjdmtgk)); 
        if (this.VMjdysms != null)
             cloned.setVMjdysms(new String(this.VMjdysms)); 
        if (this.VMjamsms != null)
             cloned.setVMjamsms(new String(this.VMjamsms)); 
        if (this.VMjamtgk != null)
             cloned.setVMjamtgk(new String(this.VMjamtgk)); 
        if (this.VMjaysms != null)
             cloned.setVMjaysms(new String(this.VMjaysms)); 
        if (this.VMjaytgk != null)
             cloned.setVMjaytgk(new String(this.VMjaytgk)); 
        if (this.VMjbmsms != null)
             cloned.setVMjbmsms(new String(this.VMjbmsms)); 
        if (this.VMjbmtgk != null)
             cloned.setVMjbmtgk(new String(this.VMjbmtgk)); 
        if (this.VMjbysms != null)
             cloned.setVMjbysms(new String(this.VMjbysms)); 
        if (this.VMjbytgk != null)
             cloned.setVMjbytgk(new String(this.VMjbytgk)); 
        if (this.VMjdytgk != null)
             cloned.setVMjdytgk(new String(this.VMjdytgk)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
