package com.epbt2.mtkn.tanya.dao;

import java.io.Serializable;

/**
 * HVmjc2 Value Object. This class is value object representing database table
 * HVMJC2 This class is intented to be used together with associated Dao object.
 */
/**
 * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
 * The usage of generated code is restricted to OpenSource software projects
 * only. DaoGen is available in http://titaniclinux.net/daogen/ It has been
 * programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
 *
 * DaoGen license: The following DaoGen generated source code is licensed under
 * the terms of GNU GPL license. The full text for license is available in GNU
 * project's pages: http://www.gnu.org/copyleft/gpl.html
 *
 * If you wish to use the DaoGen generator to produce code for closed-source
 * commercial applications, you must pay the lisence fee. The price is 5 USD or
 * 5 Eur for each database table, you are generating code for. (That includes
 * unlimited amount of iterations with all supported languages for each database
 * table you are paying for.) Send mail to "Tuomo.Lukka@iki.fi" for more
 * information. Thank you!
 */
public class HVmjc2 implements Cloneable, Serializable {

    /**
     * Persistent Instance variables. This data is directly mapped to the
     * columns of database table.
     */
    private String VMjlebh2;
    private String VMjemsms;
    private String VMjemtgk;
    private String VMjeysms;
    private String VMjeytgk;
    private String VMjfmsms;
    private String VMjfmtgk;
    private String VMjfysms;
    private String VMjfytgk;
    /*Uzzair*/
    private String SCrtgkna;
    private String SCrtgknb;
    private String SCrtgknc;
    private String SCrtgknd;

    public String getSCrtgkna() {
        return SCrtgkna;
    }

    public void setSCrtgkna(String SCrtgkna) {
        this.SCrtgkna = SCrtgkna;
    }

    public String getSCrtgknb() {
        return SCrtgknb;
    }

    public void setSCrtgknb(String SCrtgknb) {
        this.SCrtgknb = SCrtgknb;
    }

    public String getSCrtgknc() {
        return SCrtgknc;
    }

    public void setSCrtgknc(String SCrtgknc) {
        this.SCrtgknc = SCrtgknc;
    }

    public String getSCrtgknd() {
        return SCrtgknd;
    }

    public void setSCrtgknd(String SCrtgknd) {
        this.SCrtgknd = SCrtgknd;
    }
    
    
    /*smi*/
    private String VMjamsms;

    public String getVMjamsms() {
        return VMjamsms;
    }

    public void setVMjamsms(String VMjamsms) {
        this.VMjamsms = VMjamsms;
    }

    public String getVMjbmsms() {
        return VMjbmsms;
    }

    public void setVMjbmsms(String VMjbmsms) {
        this.VMjbmsms = VMjbmsms;
    }

    public String getVMjcmsms() {
        return VMjcmsms;
    }

    public void setVMjcmsms(String VMjcmsms) {
        this.VMjcmsms = VMjcmsms;
    }

    public String getVMjdmsms() {
        return VMjdmsms;
    }

    public void setVMjdmsms(String VMjdmsms) {
        this.VMjdmsms = VMjdmsms;
    }

    public String getVMjaysms() {
        return VMjaysms;
    }

    public void setVMjaysms(String VMjaysms) {
        this.VMjaysms = VMjaysms;
    }

    public String getVMjbysms() {
        return VMjbysms;
    }

    public void setVMjbysms(String VMjbysms) {
        this.VMjbysms = VMjbysms;
    }

    public String getVMjcysms() {
        return VMjcysms;
    }

    public void setVMjcysms(String VMjcysms) {
        this.VMjcysms = VMjcysms;
    }

    public String getVMjdysms() {
        return VMjdysms;
    }

    public void setVMjdysms(String VMjdysms) {
        this.VMjdysms = VMjdysms;
    }
    private String VMjbmsms;
    private String VMjcmsms;
    private String VMjdmsms;
    private String VMjaysms;
    private String VMjbysms;
    private String VMjcysms;
    private String VMjdysms;

    /*smi*/
    /**
     * Constructors. DaoGen generates two constructors by default. The first one
     * takes no arguments and provides the most simple way to create object
     * instance. The another one takes one argument, which is the primary key of
     * the corresponding table.
     */
    public HVmjc2() {

    }

    public HVmjc2(String VMjlebh2In) {

        this.VMjlebh2 = VMjlebh2In;

    }

    /**
     * Get- and Set-methods for persistent variables. The default behaviour does
     * not make any checks against malformed data, so these might require some
     * manual additions.
     */
    public String getVMjlebh2() {
        return this.VMjlebh2;
    }

    public void setVMjlebh2(String VMjlebh2In) {
        this.VMjlebh2 = VMjlebh2In;
    }

    public String getVMjemsms() {
        return this.VMjemsms;
    }

    public void setVMjemsms(String VMjemsmsIn) {
        this.VMjemsms = VMjemsmsIn;
    }

    public String getVMjemtgk() {
        return this.VMjemtgk;
    }

    public void setVMjemtgk(String VMjemtgkIn) {
        this.VMjemtgk = VMjemtgkIn;
    }

    public String getVMjeysms() {
        return this.VMjeysms;
    }

    public void setVMjeysms(String VMjeysmsIn) {
        this.VMjeysms = VMjeysmsIn;
    }

    public String getVMjeytgk() {
        return this.VMjeytgk;
    }

    public void setVMjeytgk(String VMjeytgkIn) {
        this.VMjeytgk = VMjeytgkIn;
    }

    public String getVMjfmsms() {
        return this.VMjfmsms;
    }

    public void setVMjfmsms(String VMjfmsmsIn) {
        this.VMjfmsms = VMjfmsmsIn;
    }

    public String getVMjfmtgk() {
        return this.VMjfmtgk;
    }

    public void setVMjfmtgk(String VMjfmtgkIn) {
        this.VMjfmtgk = VMjfmtgkIn;
    }

    public String getVMjfysms() {
        return this.VMjfysms;
    }

    public void setVMjfysms(String VMjfysmsIn) {
        this.VMjfysms = VMjfysmsIn;
    }

    public String getVMjfytgk() {
        return this.VMjfytgk;
    }

    public void setVMjfytgk(String VMjfytgkIn) {
        this.VMjfytgk = VMjfytgkIn;
    }

    /**
     * setAll allows to set all persistent variables in one method call. This is
     * useful, when all data is available and it is needed to set the initial
     * state of this object. Note that this method will directly modify instance
     * variales, without going trough the individual set-methods.
     */
    public void setAll(String VMjlebh2In,
            String VMjamsmsIn,
            String VMjbmsmsIn,
            String VMjcmsmsIn,
            String VMjdmsmsIn,
            String VMjaysmsIn,
            String VMjbysmsIn,
            String VMjcysmsIn,
            String VMjdysmsIn,
            String VMjemsmsIn,
            String VMjemtgkIn,
            String VMjeysmsIn,
            String VMjeytgkIn,
            String VMjfmsmsIn,
            String VMjfmtgkIn,
            String VMjfysmsIn,
            String VMjfytgkIn) {
        this.VMjamsms = VMjamsmsIn;
        this.VMjbmsms = VMjbmsmsIn;
        this.VMjcmsms = VMjcmsmsIn;
        this.VMjdmsms = VMjdmsmsIn;
        this.VMjaysms = VMjaysmsIn;
        this.VMjbysms = VMjbysmsIn;
        this.VMjcysms = VMjcysmsIn;
        this.VMjdysms = VMjdysmsIn;
        this.VMjemsms = VMjemsmsIn;
        this.VMjemtgk = VMjemtgkIn;
        this.VMjeysms = VMjeysmsIn;
        this.VMjeytgk = VMjeytgkIn;
        this.VMjfmsms = VMjfmsmsIn;
        this.VMjfmtgk = VMjfmtgkIn;
        this.VMjfysms = VMjfysmsIn;
        this.VMjfytgk = VMjfytgkIn;
    }

    /**
     * hasEqualMapping-method will compare two HVmjc2 instances and return true
     * if they contain same values in all persistent instance variables. If
     * hasEqualMapping returns true, it does not mean the objects are the same
     * instance. However it does mean that in that moment, they are mapped to
     * the same row in database.
     */
    public boolean hasEqualMapping(HVmjc2 valueObject) {
        /*hafiz start*/
        if (this.VMjamsms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjamsms.equals(valueObject.getVMjamsms())) {
            return (false);
        }
        if (this.VMjbmsms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjbmsms.equals(valueObject.getVMjbmsms())) {
            return (false);
        }
        if (this.VMjcmsms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjcmsms.equals(valueObject.getVMjcmsms())) {
            return (false);
        }
        if (this.VMjdmsms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjdmsms.equals(valueObject.getVMjdmsms())) {
            return (false);
        }
        if (this.VMjaysms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjaysms.equals(valueObject.getVMjaysms())) {
            return (false);
        }
        if (this.VMjbysms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjbysms.equals(valueObject.getVMjbysms())) {
            return (false);
        }
        if (this.VMjbysms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjbysms.equals(valueObject.getVMjbysms())) {
            return (false);
        }
        if (this.VMjcysms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjcysms.equals(valueObject.getVMjcysms())) {
            return (false);
        }
        if (this.VMjdysms == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjdysms.equals(valueObject.getVMjdysms())) {
            return (false);
        }
     

        /*hafiz end*/
        if (this.VMjlebh2 == null) {
            if (valueObject.getVMjlebh2() != null) {
                return (false);
            }
        } else if (!this.VMjlebh2.equals(valueObject.getVMjlebh2())) {
            return (false);
        }
        if (this.VMjemsms == null) {
            if (valueObject.getVMjemsms() != null) {
                return (false);
            }
        } else if (!this.VMjemsms.equals(valueObject.getVMjemsms())) {
            return (false);
        }
        if (this.VMjemtgk == null) {
            if (valueObject.getVMjemtgk() != null) {
                return (false);
            }
        } else if (!this.VMjemtgk.equals(valueObject.getVMjemtgk())) {
            return (false);
        }
        if (this.VMjeysms == null) {
            if (valueObject.getVMjeysms() != null) {
                return (false);
            }
        } else if (!this.VMjeysms.equals(valueObject.getVMjeysms())) {
            return (false);
        }
        if (this.VMjeytgk == null) {
            if (valueObject.getVMjeytgk() != null) {
                return (false);
            }
        } else if (!this.VMjeytgk.equals(valueObject.getVMjeytgk())) {
            return (false);
        }
        if (this.VMjfmsms == null) {
            if (valueObject.getVMjfmsms() != null) {
                return (false);
            }
        } else if (!this.VMjfmsms.equals(valueObject.getVMjfmsms())) {
            return (false);
        }
        if (this.VMjfmtgk == null) {
            if (valueObject.getVMjfmtgk() != null) {
                return (false);
            }
        } else if (!this.VMjfmtgk.equals(valueObject.getVMjfmtgk())) {
            return (false);
        }
        if (this.VMjfysms == null) {
            if (valueObject.getVMjfysms() != null) {
                return (false);
            }
        } else if (!this.VMjfysms.equals(valueObject.getVMjfysms())) {
            return (false);
        }
        if (this.VMjfytgk == null) {
            if (valueObject.getVMjfytgk() != null) {
                return (false);
            }
        } else if (!this.VMjfytgk.equals(valueObject.getVMjfytgk())) {
            return (false);
        }

        return true;
    }

    /**
     * toString will return String object representing the state of this
     * valueObject. This is useful during application development, and possibly
     * when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass HVmjc2, mapping to table HVMJC2\n");
        out.append("Persistent attributes: \n");
        /*hafiz*/
        out.append("VMjamsms = " + this.VMjamsms + "\n");
        out.append("VMjbmsms = " + this.VMjbmsms + "\n");
        out.append("VMjcmsms = " + this.VMjcmsms + "\n");
        out.append("VMjdmsms = " + this.VMjdmsms + "\n");
        
        
        out.append("VMjaysms = " + this.VMjaysms + "\n");
        out.append("VMjbysms = " + this.VMjbysms + "\n");
        out.append("VMjcysms = " + this.VMjcysms + "\n");
        out.append("VMjdysms = " + this.VMjdysms + "\n");
        
        
        /*hafiz end*/
        out.append("VMjlebh2 = " + this.VMjlebh2 + "\n");
        out.append("VMjemsms = " + this.VMjemsms + "\n");
        out.append("VMjemtgk = " + this.VMjemtgk + "\n");
        out.append("VMjeysms = " + this.VMjeysms + "\n");
        out.append("VMjeytgk = " + this.VMjeytgk + "\n");
        out.append("VMjfmsms = " + this.VMjfmsms + "\n");
        out.append("VMjfmtgk = " + this.VMjfmtgk + "\n");
        out.append("VMjfysms = " + this.VMjfysms + "\n");
        out.append("VMjfytgk = " + this.VMjfytgk + "\n");
        return out.toString();
    }

    /**
     * Clone will return identical deep copy of this valueObject. Note, that
     * this method is different than the clone() which is defined in
     * java.lang.Object. Here, the retuned cloned object will also have all its
     * attributes cloned.
     */
    public Object clone() {
        HVmjc2 cloned = new HVmjc2();
/*HAFIZ START*/
        if (this.VMjamsms != null) {
            cloned.setVMjlebh2(new String(this.VMjamsms));
        }
        if (this.VMjbmsms != null) {
            cloned.setVMjbmsms(new String(this.VMjbmsms));
        }
        if (this.VMjcmsms != null) {
            cloned.setVMjcmsms(new String(this.VMjcmsms));
        }
        if (this.VMjdmsms != null) {
            cloned.setVMjdmsms(new String(this.VMjdmsms));
        }
        
        if (this.VMjaysms != null) {
            cloned.setVMjaysms(new String(this.VMjaysms));
        }
        if (this.VMjbysms != null) {
            cloned.setVMjbysms(new String(this.VMjbysms));
        }
        if (this.VMjcysms != null) {
            cloned.setVMjcysms(new String(this.VMjcysms));
        }
        if (this.VMjdysms != null) {
            cloned.setVMjdysms(new String(this.VMjdysms));
        }
        
/*HAFIZ END*/
        
        if (this.VMjlebh2 != null) {
            cloned.setVMjlebh2(new String(this.VMjlebh2));
        }
        if (this.VMjemsms != null) {
            cloned.setVMjemsms(new String(this.VMjemsms));
        }
        if (this.VMjemtgk != null) {
            cloned.setVMjemtgk(new String(this.VMjemtgk));
        }
        if (this.VMjeysms != null) {
            cloned.setVMjeysms(new String(this.VMjeysms));
        }
        if (this.VMjeytgk != null) {
            cloned.setVMjeytgk(new String(this.VMjeytgk));
        }
        if (this.VMjfmsms != null) {
            cloned.setVMjfmsms(new String(this.VMjfmsms));
        }
        if (this.VMjfmtgk != null) {
            cloned.setVMjfmtgk(new String(this.VMjfmtgk));
        }
        if (this.VMjfysms != null) {
            cloned.setVMjfysms(new String(this.VMjfysms));
        }
        if (this.VMjfytgk != null) {
            cloned.setVMjfytgk(new String(this.VMjfytgk));
        }
        return cloned;
    }

    /**
     * getDaogenVersion will return information about generator which created
     * these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
