package com.epbt2.mtkn.pemprosesan.dao;

import java.io.Serializable;

 /**
  * Hlcmk1 Value Object.
  * This class is value object representing database table MTKN.HLCMK1
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Hlcmk1 implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String cm1Jbkod;
    private String cm1Nobil;
    private String cm1Tkhbl;
    private String cm1Tmpoh;
    private String cm1Statf;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Hlcmk1 () {

    }

    public Hlcmk1 (String cm1JbkodIn, String cm1NobilIn) {

          this.cm1Jbkod = cm1JbkodIn;
          this.cm1Nobil = cm1NobilIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getCm1Jbkod() {
          return this.cm1Jbkod;
    }
    public void setCm1Jbkod(String cm1JbkodIn) {
          this.cm1Jbkod = cm1JbkodIn;
    }

    public String getCm1Nobil() {
          return this.cm1Nobil;
    }
    public void setCm1Nobil(String cm1NobilIn) {
          this.cm1Nobil = cm1NobilIn;
    }

    public String getCm1Tkhbl() {
          return this.cm1Tkhbl;
    }
    public void setCm1Tkhbl(String cm1TkhblIn) {
          this.cm1Tkhbl = cm1TkhblIn;
    }

    public String getCm1Tmpoh() {
          return this.cm1Tmpoh;
    }
    public void setCm1Tmpoh(String cm1TmpohIn) {
          this.cm1Tmpoh = cm1TmpohIn;
    }

    public String getCm1Statf() {
          return this.cm1Statf;
    }
    public void setCm1Statf(String cm1StatfIn) {
          this.cm1Statf = cm1StatfIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String cm1JbkodIn,
          String cm1NobilIn,
          String cm1TkhblIn,
          String cm1TmpohIn,
          String cm1StatfIn) {
          this.cm1Jbkod = cm1JbkodIn;
          this.cm1Nobil = cm1NobilIn;
          this.cm1Tkhbl = cm1TkhblIn;
          this.cm1Tmpoh = cm1TmpohIn;
          this.cm1Statf = cm1StatfIn;
    }


    /** 
     * hasEqualMapping-method will compare two Hlcmk1 instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Hlcmk1 valueObject) {

          if (valueObject.getCm1Jbkod() != this.cm1Jbkod) {
                    return(false);
          }
          if (valueObject.getCm1Nobil() != this.cm1Nobil) {
                    return(false);
          }
          if (this.cm1Tkhbl == null) {
                    if (valueObject.getCm1Tkhbl() != null)
                           return(false);
          } else if (!this.cm1Tkhbl.equals(valueObject.getCm1Tkhbl())) {
                    return(false);
          }
          if (this.cm1Tmpoh == null) {
                    if (valueObject.getCm1Tmpoh() != null)
                           return(false);
          } else if (!this.cm1Tmpoh.equals(valueObject.getCm1Tmpoh())) {
                    return(false);
          }
          if (this.cm1Statf == null) {
                    if (valueObject.getCm1Statf() != null)
                           return(false);
          } else if (!this.cm1Statf.equals(valueObject.getCm1Statf())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Hlcmk1, mapping to table MTKN.HLCMK1\n");
        out.append("Persistent attributes: \n"); 
        out.append("cm1Jbkod = " + this.cm1Jbkod + "\n"); 
        out.append("cm1Nobil = " + this.cm1Nobil + "\n"); 
        out.append("cm1Tkhbl = " + this.cm1Tkhbl + "\n"); 
        out.append("cm1Tmpoh = " + this.cm1Tmpoh + "\n"); 
        out.append("cm1Statf = " + this.cm1Statf + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Hlcmk1 cloned = new Hlcmk1();

        cloned.setCm1Jbkod(this.cm1Jbkod); 
        cloned.setCm1Nobil(this.cm1Nobil); 
        if (this.cm1Tkhbl != null)
             cloned.setCm1Tkhbl(new String(this.cm1Tkhbl)); 
        if (this.cm1Tmpoh != null)
             cloned.setCm1Tmpoh(new String(this.cm1Tmpoh)); 
        if (this.cm1Statf != null)
             cloned.setCm1Statf(new String(this.cm1Statf)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}