package com.epbt2.mtkn.pemprosesan.dao;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Hlkbc2 Value Object.
  * This class is value object representing database table MTKN.HLKBC2
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Hlkbc2 implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String bc2Akaun;
    private String bc2Kdrjk;
    private String bc2Nobil;
    private String bc2Amaun;
    private String bc2Statf;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Hlkbc2 () {

    }

    public Hlkbc2 (String bc2AkaunIn, String bc2KdrjkIn) {

          this.bc2Akaun = bc2AkaunIn;
          this.bc2Kdrjk = bc2KdrjkIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getBc2Akaun() {
          return this.bc2Akaun;
    }
    public void setBc2Akaun(String bc2AkaunIn) {
          this.bc2Akaun = bc2AkaunIn;
    }

    public String getBc2Kdrjk() {
          return this.bc2Kdrjk;
    }
    public void setBc2Kdrjk(String bc2KdrjkIn) {
          this.bc2Kdrjk = bc2KdrjkIn;
    }

    public String getBc2Nobil() {
          return this.bc2Nobil;
    }
    public void setBc2Nobil(String bc2NobilIn) {
          this.bc2Nobil = bc2NobilIn;
    }

    public String getBc2Amaun() {
          return this.bc2Amaun;
    }
    public void setBc2Amaun(String bc2AmaunIn) {
          this.bc2Amaun = bc2AmaunIn;
    }

    public String getBc2Statf() {
          return this.bc2Statf;
    }
    public void setBc2Statf(String bc2StatfIn) {
          this.bc2Statf = bc2StatfIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String bc2AkaunIn,
          String bc2KdrjkIn,
          String bc2NobilIn,
          String bc2AmaunIn,
          String bc2StatfIn) {
          this.bc2Akaun = bc2AkaunIn;
          this.bc2Kdrjk = bc2KdrjkIn;
          this.bc2Nobil = bc2NobilIn;
          this.bc2Amaun = bc2AmaunIn;
          this.bc2Statf = bc2StatfIn;
    }


    /** 
     * hasEqualMapping-method will compare two Hlkbc2 instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Hlkbc2 valueObject) {

          if (this.bc2Akaun == null) {
                    if (valueObject.getBc2Akaun() != null)
                           return(false);
          } else if (!this.bc2Akaun.equals(valueObject.getBc2Akaun())) {
                    return(false);
          }
          if (this.bc2Kdrjk == null) {
                    if (valueObject.getBc2Kdrjk() != null)
                           return(false);
          } else if (!this.bc2Kdrjk.equals(valueObject.getBc2Kdrjk())) {
                    return(false);
          }
          if (this.bc2Nobil == null) {
                    if (valueObject.getBc2Nobil() != null)
                           return(false);
          } else if (!this.bc2Nobil.equals(valueObject.getBc2Nobil())) {
                    return(false);
          }
          if (this.bc2Amaun == null) {
                    if (valueObject.getBc2Amaun() != null)
                           return(false);
          } else if (!this.bc2Amaun.equals(valueObject.getBc2Amaun())) {
                    return(false);
          }
          if (this.bc2Statf == null) {
                    if (valueObject.getBc2Statf() != null)
                           return(false);
          } else if (!this.bc2Statf.equals(valueObject.getBc2Statf())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Hlkbc2, mapping to table MTKN.HLKBC2\n");
        out.append("Persistent attributes: \n"); 
        out.append("bc2Akaun = " + this.bc2Akaun + "\n"); 
        out.append("bc2Kdrjk = " + this.bc2Kdrjk + "\n"); 
        out.append("bc2Nobil = " + this.bc2Nobil + "\n"); 
        out.append("bc2Amaun = " + this.bc2Amaun + "\n"); 
        out.append("bc2Statf = " + this.bc2Statf + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Hlkbc2 cloned = new Hlkbc2();

        if (this.bc2Akaun != null)
             cloned.setBc2Akaun(new String(this.bc2Akaun)); 
        if (this.bc2Kdrjk != null)
             cloned.setBc2Kdrjk(new String(this.bc2Kdrjk)); 
        if (this.bc2Nobil != null)
             cloned.setBc2Nobil(new String(this.bc2Nobil)); 
        if (this.bc2Amaun != null)
             cloned.setBc2Amaun(new String(this.bc2Amaun)); 
        if (this.bc2Statf != null)
             cloned.setBc2Statf(new String(this.bc2Statf)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
