package com.epbt2.mtkn.pemprosesan.dao;


import com.epbt2.util.NotFoundException;
import java.sql.*;
import java.util.*;


 /**
  * Hnotis Data Access Object (DAO).
  * This class contains all database handling that is needed to 
  * permanently store and retrieve Hnotis object instances. 
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class HnotisDao {



    /**
     * createValueObject-method. This method is used when the Dao class needs
     * to create new value object instance. The reason why this method exists
     * is that sometimes the programmer may want to extend also the valueObject
     * and then this method can be overrided to return extended valueObject.
     * NOTE: If you extend the valueObject class, make sure to override the
     * clone() method in it!
     */
    public Hnotis createValueObject() {
          return new Hnotis();
    }


    /**
     * getObject-method. This will create and load valueObject contents from database 
     * using given Primary-Key as identifier. This method is just a convenience method 
     * for the real load-method which accepts the valueObject as a parameter. Returned
     * valueObject will be created using the createValueObject() method.
     */
    public Hnotis getObject(Connection conn, String notStatf, String notAkaun) throws NotFoundException, SQLException {

          Hnotis valueObject = createValueObject();
          valueObject.setNotStatf(notStatf);
          valueObject.setNotAkaun(notAkaun);
          load(conn, valueObject);
          return valueObject;
    }


    /**
     * load-method. This will load valueObject contents from database using
     * Primary-Key as identifier. Upper layer should use this so that valueObject
     * instance is created and only primary-key should be specified. Then call
     * this method to complete other persistent information. This method will
     * overwrite all other fields except primary-key and possible runtime variables.
     * If load can not find matching row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be loaded.
     *                     Primary-key field must be set for this to work properly.
     */
    public void load(Connection conn, Hnotis valueObject) throws NotFoundException, SQLException {

          if (valueObject.getNotStatf() == null) {
               //System.out.println("Can not select without Primary-Key!");
               throw new NotFoundException("Can not select without Primary-Key!");
          }

          if (valueObject.getNotAkaun() == null) {
               //System.out.println("Can not select without Primary-Key!");
               throw new NotFoundException("Can not select without Primary-Key!");
          }

          String sql = "SELECT * FROM MTKN.HNOTIS WHERE (NOT_STATF = ? AND NOT_AKAUN = ? ) "; 
          PreparedStatement stmt = null;

          try {
               stmt = conn.prepareStatement(sql);
               stmt.setString(1, valueObject.getNotStatf()); 
               stmt.setString(2, valueObject.getNotAkaun()); 

               singleQuery(conn, stmt, valueObject);

          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * LoadAll-method. This will read all contents from database table and
     * build a List containing valueObjects. Please note, that this method
     * will consume huge amounts of resources if table has lot's of rows. 
     * This should only be used when target tables have only small amounts
     * of data.
     *
     * @param conn         This method requires working database connection.
     */
    public List loadAll(Connection conn) throws SQLException {

          String sql = "SELECT * FROM MTKN.HNOTIS ORDER BY NOT_AKAUN ASC ";
          List searchResults = listQuery(conn, conn.prepareStatement(sql));

          return searchResults;
    }



    /**
     * create-method. This will create new row in database according to supplied
     * valueObject contents. Make sure that values for all NOT NULL columns are
     * correctly specified. Also, if this table does not use automatic surrogate-keys
     * the primary-key must be specified. After INSERT command this method will 
     * read the generated primary-key back to valueObject if automatic surrogate-keys
     * were used. 
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be created.
     *                     If automatic surrogate-keys are not used the Primary-key 
     *                     field must be set for this to work properly.
     */
    public synchronized void create(Connection conn, Hnotis valueObject) throws SQLException {

          String sql = "";
          PreparedStatement stmt = null;
          ResultSet result = null;

          try {
               sql = "INSERT INTO MTKN.HNOTIS ( NOT_STATF, NOT_AKAUN, NOT_NONOT, "
               + "NOT_TKNOT, NOT_TMPOH, NOT_AMAUN, "
               + "NOT_GENAP, NOT_CTSMS, NOT_CTTGK, "
               + "NOT_DNSMS, NOT_DNTGK, NOT_NTSMS, "
               + "NOT_NTTGK, NOT_WRSMS, NOT_WRTGK, "
               + "NOT_ALSMS, NOT_ALTGK) VALUES (?, ?, ?, TO_DATE(?,'DD/MM/YYYY'), TO_DATE(?,'DD/MM/YYYY'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";
               stmt = conn.prepareStatement(sql);

               stmt.setString(1, valueObject.getNotStatf()); 
               stmt.setString(2, valueObject.getNotAkaun()); 
               stmt.setString(3, valueObject.getNotNonot()); 
               stmt.setString(4, valueObject.getNotTknot()); 
               stmt.setString(5, valueObject.getNotTmpoh()); 
               stmt.setString(6, valueObject.getNotAmaun()); 
               stmt.setString(7, valueObject.getNotGenap()); 
               stmt.setString(8, valueObject.getNotCtsms()); 
               stmt.setString(9, valueObject.getNotCttgk()); 
               stmt.setString(10, valueObject.getNotDnsms()); 
               stmt.setString(11, valueObject.getNotDntgk()); 
               stmt.setString(12, valueObject.getNotNtsms()); 
               stmt.setString(13, valueObject.getNotNttgk()); 
               stmt.setString(14, valueObject.getNotWrsms()); 
               stmt.setString(15, valueObject.getNotWrtgk()); 
               stmt.setString(16, valueObject.getNotAlsms()); 
               stmt.setString(17, valueObject.getNotAltgk()); 

               int rowcount = databaseUpdate(conn, stmt);
               if (rowcount != 1) {
                    //System.out.println("PrimaryKey Error when updating DB!");
                    throw new SQLException("PrimaryKey Error when updating DB!");
               }

          } finally {
              if (stmt != null)
                  stmt.close();
          }


    }


    /**
     * save-method. This method will save the current state of valueObject to database.
     * Save can not be used to create new instances in database, so upper layer must
     * make sure that the primary-key is correctly specified. Primary-key will indicate
     * which instance is going to be updated in database. If save can not find matching 
     * row, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be saved.
     *                     Primary-key field must be set for this to work properly.
     */
    public void save(Connection conn, Hnotis valueObject) 
          throws NotFoundException, SQLException {

          String sql = "UPDATE MTKN.HNOTIS SET NOT_NONOT = ?, NOT_TKNOT = ?, NOT_TMPOH = ?, "
               + "NOT_AMAUN = ?, NOT_GENAP = ?, NOT_CTSMS = ?, "
               + "NOT_CTTGK = ?, NOT_DNSMS = ?, NOT_DNTGK = ?, "
               + "NOT_NTSMS = ?, NOT_NTTGK = ?, NOT_WRSMS = ?, "
               + "NOT_WRTGK = ?, NOT_ALSMS = ?, NOT_ALTGK = ? WHERE (NOT_STATF = ? AND NOT_AKAUN = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getNotNonot()); 
              stmt.setString(2, valueObject.getNotTknot()); 
              stmt.setString(3, valueObject.getNotTmpoh()); 
              stmt.setString(4, valueObject.getNotAmaun()); 
              stmt.setString(5, valueObject.getNotGenap()); 
              stmt.setString(6, valueObject.getNotCtsms()); 
              stmt.setString(7, valueObject.getNotCttgk()); 
              stmt.setString(8, valueObject.getNotDnsms()); 
              stmt.setString(9, valueObject.getNotDntgk()); 
              stmt.setString(10, valueObject.getNotNtsms()); 
              stmt.setString(11, valueObject.getNotNttgk()); 
              stmt.setString(12, valueObject.getNotWrsms()); 
              stmt.setString(13, valueObject.getNotWrtgk()); 
              stmt.setString(14, valueObject.getNotAlsms()); 
              stmt.setString(15, valueObject.getNotAltgk()); 

              stmt.setString(16, valueObject.getNotStatf()); 
              stmt.setString(17, valueObject.getNotAkaun()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be saved! (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be saved! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were affected!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were affected!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * delete-method. This method will remove the information from database as identified by
     * by primary-key in supplied valueObject. Once valueObject has been deleted it can not 
     * be restored by calling save. Restoring can only be done using create method but if 
     * database is using automatic surrogate-keys, the resulting object will have different 
     * primary-key than what it was in the deleted object. If delete can not find matching row,
     * NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance to be deleted.
     *                     Primary-key field must be set for this to work properly.
     */
    public void delete(Connection conn, Hnotis valueObject) 
          throws NotFoundException, SQLException {

          if (valueObject.getNotStatf() == null) {
               //System.out.println("Can not delete without Primary-Key!");
               throw new NotFoundException("Can not delete without Primary-Key!");
          }

          if (valueObject.getNotAkaun() == null) {
               //System.out.println("Can not delete without Primary-Key!");
               throw new NotFoundException("Can not delete without Primary-Key!");
          }

          String sql = "DELETE FROM MTKN.HNOTIS WHERE (NOT_STATF = ? AND NOT_AKAUN = ? ) ";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              stmt.setString(1, valueObject.getNotStatf()); 
              stmt.setString(2, valueObject.getNotAkaun()); 

              int rowcount = databaseUpdate(conn, stmt);
              if (rowcount == 0) {
                   //System.out.println("Object could not be deleted (PrimaryKey not found)");
                   throw new NotFoundException("Object could not be deleted! (PrimaryKey not found)");
              }
              if (rowcount > 1) {
                   //System.out.println("PrimaryKey Error when updating DB! (Many objects were deleted!)");
                   throw new SQLException("PrimaryKey Error when updating DB! (Many objects were deleted!)");
              }
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * deleteAll-method. This method will remove all information from the table that matches
     * this Dao and ValueObject couple. This should be the most efficient way to clear table.
     * Once deleteAll has been called, no valueObject that has been created before can be 
     * restored by calling save. Restoring can only be done using create method but if database 
     * is using automatic surrogate-keys, the resulting object will have different primary-key 
     * than what it was in the deleted object. (Note, the implementation of this method should
     * be different with different DB backends.)
     *
     * @param conn         This method requires working database connection.
     */
    public void deleteAll(Connection conn) throws SQLException {

          String sql = "DELETE FROM MTKN.HNOTIS";
          PreparedStatement stmt = null;

          try {
              stmt = conn.prepareStatement(sql);
              int rowcount = databaseUpdate(conn, stmt);
          } finally {
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * coutAll-method. This method will return the number of all rows from table that matches
     * this Dao. The implementation will simply execute "select count(primarykey) from table".
     * If table is empty, the return value is 0. This method should be used before calling
     * loadAll, to make sure table has not too many rows.
     *
     * @param conn         This method requires working database connection.
     */
    public int countAll(Connection conn) throws SQLException {

          String sql = "SELECT count(*) FROM MTKN.HNOTIS";
          PreparedStatement stmt = null;
          ResultSet result = null;
          int allRows = 0;

          try {
              stmt = conn.prepareStatement(sql);
              result = stmt.executeQuery();

              if (result.next())
                  allRows = result.getInt(1);
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
          return allRows;
    }


    /** 
     * searchMatching-Method. This method provides searching capability to 
     * get matching valueObjects from database. It works by searching all 
     * objects that match permanent instance variables of given object.
     * Upper layer should use this by setting some parameters in valueObject
     * and then  call searchMatching. The result will be 0-N objects in a List, 
     * all matching those criteria you specified. Those instance-variables that
     * have NULL values are excluded in search-criteria.
     *
     * @param conn         This method requires working database connection.
     * @param valueObject  This parameter contains the class instance where search will be based.
     *                     Primary-key field should not be set.
     */
    public List searchMatching(Connection conn, Hnotis valueObject) throws SQLException {

          List searchResults;

          boolean first = true;
          StringBuffer sql = new StringBuffer("SELECT * FROM MTKN.HNOTIS WHERE 1=1 ");

          if (valueObject.getNotStatf() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_STATF LIKE '").append(valueObject.getNotStatf()).append("%' ");
          }

          if (valueObject.getNotAkaun() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_AKAUN LIKE '").append(valueObject.getNotAkaun()).append("%' ");
          }

          if (valueObject.getNotNonot() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_NONOT LIKE '").append(valueObject.getNotNonot()).append("%' ");
          }

          if (valueObject.getNotTknot() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_TKNOT LIKE '").append(valueObject.getNotTknot()).append("%' ");
          }

          if (valueObject.getNotTmpoh() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_TMPOH LIKE '").append(valueObject.getNotTmpoh()).append("%' ");
          }

          if (valueObject.getNotAmaun() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_AMAUN LIKE '").append(valueObject.getNotAmaun()).append("%' ");
          }

          if (valueObject.getNotGenap() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_GENAP LIKE '").append(valueObject.getNotGenap()).append("%' ");
          }

          if (valueObject.getNotCtsms() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_CTSMS LIKE '").append(valueObject.getNotCtsms()).append("%' ");
          }

          if (valueObject.getNotCttgk() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_CTTGK LIKE '").append(valueObject.getNotCttgk()).append("%' ");
          }

          if (valueObject.getNotDnsms() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_DNSMS LIKE '").append(valueObject.getNotDnsms()).append("%' ");
          }

          if (valueObject.getNotDntgk() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_DNTGK LIKE '").append(valueObject.getNotDntgk()).append("%' ");
          }

          if (valueObject.getNotNtsms() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_NTSMS LIKE '").append(valueObject.getNotNtsms()).append("%' ");
          }

          if (valueObject.getNotNttgk() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_NTTGK LIKE '").append(valueObject.getNotNttgk()).append("%' ");
          }

          if (valueObject.getNotWrsms() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_WRSMS LIKE '").append(valueObject.getNotWrsms()).append("%' ");
          }

          if (valueObject.getNotWrtgk() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_WRTGK LIKE '").append(valueObject.getNotWrtgk()).append("%' ");
          }

          if (valueObject.getNotAlsms() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_ALSMS LIKE '").append(valueObject.getNotAlsms()).append("%' ");
          }

          if (valueObject.getNotAltgk() != null) {
              if (first) { first = false; }
              sql.append("AND NOT_ALTGK LIKE '").append(valueObject.getNotAltgk()).append("%' ");
          }


          sql.append("ORDER BY NOT_AKAUN ASC ");

          // Prevent accidential full table results.
          // Use loadAll if all rows must be returned.
          if (first)
               searchResults = new ArrayList();
          else
               searchResults = listQuery(conn, conn.prepareStatement(sql.toString()));

          return searchResults;
    }


    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }


    /**
     * databaseUpdate-method. This method is a helper method for internal use. It will execute
     * all database handling that will change the information in tables. SELECT queries will
     * not be executed here however. The return value indicates how many rows were affected.
     * This method will also make sure that if cache is used, it will reset when data changes.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected int databaseUpdate(Connection conn, PreparedStatement stmt) throws SQLException {

          int result = stmt.executeUpdate();

          return result;
    }



    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return only one row. The resultset will be converted
     * to valueObject. If no rows were found, NotFoundException will be thrown.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     * @param valueObject  Class-instance where resulting data will be stored.
     */
    protected void singleQuery(Connection conn, PreparedStatement stmt, Hnotis valueObject) 
          throws NotFoundException, SQLException {

          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              if (result.next()) {

                   valueObject.setNotStatf(result.getString("NOT_STATF")); 
                   valueObject.setNotAkaun(result.getString("NOT_AKAUN")); 
                   valueObject.setNotNonot(result.getString("NOT_NONOT")); 
                   valueObject.setNotTknot(result.getString("NOT_TKNOT")); 
                   valueObject.setNotTmpoh(result.getString("NOT_TMPOH")); 
                   valueObject.setNotAmaun(result.getString("NOT_AMAUN")); 
                   valueObject.setNotGenap(result.getString("NOT_GENAP")); 
                   valueObject.setNotCtsms(result.getString("NOT_CTSMS")); 
                   valueObject.setNotCttgk(result.getString("NOT_CTTGK")); 
                   valueObject.setNotDnsms(result.getString("NOT_DNSMS")); 
                   valueObject.setNotDntgk(result.getString("NOT_DNTGK")); 
                   valueObject.setNotNtsms(result.getString("NOT_NTSMS")); 
                   valueObject.setNotNttgk(result.getString("NOT_NTTGK")); 
                   valueObject.setNotWrsms(result.getString("NOT_WRSMS")); 
                   valueObject.setNotWrtgk(result.getString("NOT_WRTGK")); 
                   valueObject.setNotAlsms(result.getString("NOT_ALSMS")); 
                   valueObject.setNotAltgk(result.getString("NOT_ALTGK")); 

              } else {
                    //System.out.println("Hnotis Object Not Found!");
                    throw new NotFoundException("Hnotis Object Not Found!");
              }
          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }
    }


    /**
     * databaseQuery-method. This method is a helper method for internal use. It will execute
     * all database queries that will return multiple rows. The resultset will be converted
     * to the List of valueObjects. If no rows were found, an empty List will be returned.
     *
     * @param conn         This method requires working database connection.
     * @param stmt         This parameter contains the SQL statement to be excuted.
     */
    protected List listQuery(Connection conn, PreparedStatement stmt) throws SQLException {

          ArrayList searchResults = new ArrayList();
          ResultSet result = null;

          try {
              result = stmt.executeQuery();

              while (result.next()) {
                   Hnotis temp = createValueObject();

                   temp.setNotStatf(result.getString("NOT_STATF")); 
                   temp.setNotAkaun(result.getString("NOT_AKAUN")); 
                   temp.setNotNonot(result.getString("NOT_NONOT")); 
                   temp.setNotTknot(result.getString("NOT_TKNOT")); 
                   temp.setNotTmpoh(result.getString("NOT_TMPOH")); 
                   temp.setNotAmaun(result.getString("NOT_AMAUN")); 
                   temp.setNotGenap(result.getString("NOT_GENAP")); 
                   temp.setNotCtsms(result.getString("NOT_CTSMS")); 
                   temp.setNotCttgk(result.getString("NOT_CTTGK")); 
                   temp.setNotDnsms(result.getString("NOT_DNSMS")); 
                   temp.setNotDntgk(result.getString("NOT_DNTGK")); 
                   temp.setNotNtsms(result.getString("NOT_NTSMS")); 
                   temp.setNotNttgk(result.getString("NOT_NTTGK")); 
                   temp.setNotWrsms(result.getString("NOT_WRSMS")); 
                   temp.setNotWrtgk(result.getString("NOT_WRTGK")); 
                   temp.setNotAlsms(result.getString("NOT_ALSMS")); 
                   temp.setNotAltgk(result.getString("NOT_ALTGK")); 

                   searchResults.add(temp);
              }

          } finally {
              if (result != null)
                  result.close();
              if (stmt != null)
                  stmt.close();
          }

          return (List)searchResults;
    }


}
