package com.epbt2.mtkn.common.dao;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * FJalan Value Object.
  * This class is value object representing database table SPBT.FJALAN
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class FJalan implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String JlnKwkod;
    private String JlnJlkod;
    private String JlnJnama;
    private String JlnPoskd;
    
    //Tambahan Popup
    private String carian;
    private String fieldCarian;
    private String kod;
    private String nama;
    private String poskod;


    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public FJalan () {

    }

    public FJalan (String JlnKwkodIn) {

          this.JlnKwkod = JlnKwkodIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getJlnKwkod() {
          return this.JlnKwkod;
    }
    public void setJlnKwkod(String JlnKwkodIn) {
          this.JlnKwkod = JlnKwkodIn;
    }

    public String getJlnJlkod() {
          return this.JlnJlkod;
    }
    public void setJlnJlkod(String JlnJlkodIn) {
          this.JlnJlkod = JlnJlkodIn;
    }

    public String getJlnJnama() {
          return this.JlnJnama;
    }
    public void setJlnJnama(String JlnJnamaIn) {
          this.JlnJnama = JlnJnamaIn;
    }

    public String getJlnPoskd() {
          return this.JlnPoskd;
    }
    public void setJlnPoskd(String JlnPoskdIn) {
          this.JlnPoskd = JlnPoskdIn;
    }

    public String getCarian() {
        return carian;
    }

    public void setCarian(String carian) {
        this.carian = carian;
    }

    public String getFieldCarian() {
        return fieldCarian;
    }

    public void setFieldCarian(String fieldCarian) {
        this.fieldCarian = fieldCarian;
    }

    public String getKod() {
        return kod;
    }

    public void setKod(String kod) {
        this.kod = kod;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getPoskod() {
        return poskod;
    }

    public void setPoskod(String poskod) {
        this.poskod = poskod;
    }

    


    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String JlnKwkodIn,
          String JlnJlkodIn,
          String JlnJnamaIn,
          String JlnPoskdIn) {
          this.JlnKwkod = JlnKwkodIn;
          this.JlnJlkod = JlnJlkodIn;
          this.JlnJnama = JlnJnamaIn;
          this.JlnPoskd = JlnPoskdIn;
    }


    /** 
     * hasEqualMapping-method will compare two FJalan instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(FJalan valueObject) {

          if (this.JlnKwkod == null) {
                    if (valueObject.getJlnKwkod() != null)
                           return(false);
          } else if (!this.JlnKwkod.equals(valueObject.getJlnKwkod())) {
                    return(false);
          }
          if (this.JlnJlkod == null) {
                    if (valueObject.getJlnJlkod() != null)
                           return(false);
          } else if (!this.JlnJlkod.equals(valueObject.getJlnJlkod())) {
                    return(false);
          }
          if (this.JlnJnama == null) {
                    if (valueObject.getJlnJnama() != null)
                           return(false);
          } else if (!this.JlnJnama.equals(valueObject.getJlnJnama())) {
                    return(false);
          }
          if (this.JlnPoskd == null) {
                    if (valueObject.getJlnPoskd() != null)
                           return(false);
          } else if (!this.JlnPoskd.equals(valueObject.getJlnPoskd())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass FJalan, mapping to table SPBT.FJALAN\n");
        out.append("Persistent attributes: \n"); 
        out.append("JlnKwkod = " + this.JlnKwkod + "\n"); 
        out.append("JlnJlkod = " + this.JlnJlkod + "\n"); 
        out.append("JlnJnama = " + this.JlnJnama + "\n"); 
        out.append("JlnPoskd = " + this.JlnPoskd + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        FJalan cloned = new FJalan();

        if (this.JlnKwkod != null)
             cloned.setJlnKwkod(new String(this.JlnKwkod)); 
        if (this.JlnJlkod != null)
             cloned.setJlnJlkod(new String(this.JlnJlkod)); 
        if (this.JlnJnama != null)
             cloned.setJlnJnama(new String(this.JlnJnama)); 
        if (this.JlnPoskd != null)
             cloned.setJlnPoskd(new String(this.JlnPoskd)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

