package com.epbt2.mtkn.common.dao;


import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Msggpr Value Object.
  * This class is value object representing database table MTKN.MSGGPR
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Msggpr implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String mnmsej;
    private String mnmsj1;
    private String mnmsj2;
    private String mmesin;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Msggpr () {

    }

    public Msggpr (String mnmsejIn) {

          this.mnmsej = mnmsejIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getMnmsej() {
          return this.mnmsej;
    }
    public void setMnmsej(String mnmsejIn) {
          this.mnmsej = mnmsejIn;
    }

    public String getMnmsj1() {
          return this.mnmsj1;
    }
    public void setMnmsj1(String mnmsj1In) {
          this.mnmsj1 = mnmsj1In;
    }

    public String getMnmsj2() {
          return this.mnmsj2;
    }
    public void setMnmsj2(String mnmsj2In) {
          this.mnmsj2 = mnmsj2In;
    }

    public String getMmesin() {
          return this.mmesin;
    }
    public void setMmesin(String mmesinIn) {
          this.mmesin = mmesinIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String mnmsejIn,
          String mnmsj1In,
          String mnmsj2In,
          String mmesinIn) {
          this.mnmsej = mnmsejIn;
          this.mnmsj1 = mnmsj1In;
          this.mnmsj2 = mnmsj2In;
          this.mmesin = mmesinIn;
    }


    /** 
     * hasEqualMapping-method will compare two Msggpr instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Msggpr valueObject) {

          if (this.mnmsej == null) {
                    if (valueObject.getMnmsej() != null)
                           return(false);
          } else if (!this.mnmsej.equals(valueObject.getMnmsej())) {
                    return(false);
          }
          if (this.mnmsj1 == null) {
                    if (valueObject.getMnmsj1() != null)
                           return(false);
          } else if (!this.mnmsj1.equals(valueObject.getMnmsj1())) {
                    return(false);
          }
          if (this.mnmsj2 == null) {
                    if (valueObject.getMnmsj2() != null)
                           return(false);
          } else if (!this.mnmsj2.equals(valueObject.getMnmsj2())) {
                    return(false);
          }
          if (this.mmesin == null) {
                    if (valueObject.getMmesin() != null)
                           return(false);
          } else if (!this.mmesin.equals(valueObject.getMmesin())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Msggpr, mapping to table MTKN.MSGGPR\n");
        out.append("Persistent attributes: \n"); 
        out.append("mnmsej = " + this.mnmsej + "\n"); 
        out.append("mnmsj1 = " + this.mnmsj1 + "\n"); 
        out.append("mnmsj2 = " + this.mnmsj2 + "\n"); 
        out.append("mmesin = " + this.mmesin + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Msggpr cloned = new Msggpr();

        if (this.mnmsej != null)
             cloned.setMnmsej(new String(this.mnmsej)); 
        if (this.mnmsj1 != null)
             cloned.setMnmsj1(new String(this.mnmsj1)); 
        if (this.mnmsj2 != null)
             cloned.setMnmsj2(new String(this.mnmsj2)); 
        if (this.mmesin != null)
             cloned.setMmesin(new String(this.mmesin)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}